#include "base.h"

#define M3D_EFFECT_LIFE_POD0	M3D_TOTAL_TYPE(1, M3D_EFFECT)
#define M3D_ATTRACTION M3D_TOTAL_TYPE(15, M3D_EFFECT)

#define M3D_CHECK_POINT0	M3D_TOTAL_TYPE(18, M3D_EFFECT)
#define M3D_CHECK_POINT1	M3D_TOTAL_TYPE(22, M3D_EFFECT)

#define M3D_EXPLODE_WAVE		M3D_TOTAL_TYPE(32, M3D_EFFECT)

#define	M3D_HELIX_SLIME			M3D_TOTAL_TYPE(36, M3D_EFFECT)

#define	M3D_SLIME_LOOP			M3D_TOTAL_TYPE(38, M3D_EFFECT)

#define M3D_WORMBODY0			M3D_TOTAL_TYPE(47, M3D_EFFECT)
#define M3D_WORMBODY1			M3D_TOTAL_TYPE(48, M3D_EFFECT)

#define M3D_PETARDBODY			M3D_TOTAL_TYPE(49, M3D_EFFECT)

#define M3D_HAIR				M3D_TOTAL_TYPE(53, M3D_EFFECT)

#define M3D_TELEPORT_GROUND		M3D_TOTAL_TYPE(54, M3D_EFFECT)
#define M3D_TELEPORT_LIGHT		M3D_TOTAL_TYPE(55, M3D_EFFECT)

#define M3D_START_GREEN_S		M3D_TOTAL_TYPE(60, M3D_EFFECT)
#define M3D_START_GREEN_T		M3D_TOTAL_TYPE(61, M3D_EFFECT)
#define M3D_START_GREEN_A		M3D_TOTAL_TYPE(62, M3D_EFFECT)
#define M3D_START_GREEN_R		M3D_TOTAL_TYPE(63, M3D_EFFECT)

#define M3D_START_RED_S			M3D_TOTAL_TYPE(64, M3D_EFFECT)
#define M3D_START_RED_T			M3D_TOTAL_TYPE(65, M3D_EFFECT)
#define M3D_START_RED_A			M3D_TOTAL_TYPE(66, M3D_EFFECT)
#define M3D_START_RED_R			M3D_TOTAL_TYPE(67, M3D_EFFECT)

#define M3D_SMILE_HEAD		M3D_TOTAL_TYPE(70, M3D_EFFECT)

#define M3D_FX_BLANK		M3D_TOTAL_TYPE(71, M3D_EFFECT)

#define M3D_FX_REVOLT_OBJECT		M3D_TOTAL_TYPE(72, M3D_EFFECT)
#define M3D_FX_WAVE_OBJECT			M3D_TOTAL_TYPE(73, M3D_EFFECT)

#define M3D_MENU_TELEPORT_OBJECT	M3D_TOTAL_TYPE(74, M3D_EFFECT)


//--------------------- SHared XReal IDs-----------------------

#define M3D_METEORS_NUMBER	5

#define M3D_METEOR0				M3D_TOTAL_TYPE(200, M3D_XREAL)
#define M3D_METEOR1				M3D_TOTAL_TYPE(201, M3D_XREAL)
#define M3D_METEOR2				M3D_TOTAL_TYPE(202, M3D_XREAL)
#define M3D_METEOR3				M3D_TOTAL_TYPE(203, M3D_XREAL)
#define M3D_METEOR4				M3D_TOTAL_TYPE(204, M3D_XREAL)

#define M3D_CANNON_BALL			M3D_TOTAL_TYPE(205, M3D_XREAL)
#define M3D_EXPLODE_SPLINTER	M3D_TOTAL_TYPE(211, M3D_XREAL)
#define M3D_SNOWBALL			M3D_TOTAL_TYPE(212, M3D_XREAL)
#define M3D_PETARD0				M3D_TOTAL_TYPE(206, M3D_XREAL)
#define M3D_PETARD1				M3D_TOTAL_TYPE(207, M3D_XREAL)

#define M3D_PETARD2				M3D_TOTAL_TYPE(208, M3D_XREAL)
#define M3D_PETARD3				M3D_TOTAL_TYPE(209, M3D_XREAL)
#define M3D_MORTAR				M3D_TOTAL_TYPE(210, M3D_XREAL)
#define M3D_FIRE_BALL			M3D_TOTAL_TYPE(213, M3D_XREAL)
#define M3D_MORNING_STAR		M3D_TOTAL_TYPE(214, M3D_XREAL)
