
#define IW_ENTER_TELEPORT_EV		1
#define IW_EXIT_TELEPORT_EV		2
#define IW_TELEPORT_EV			3
#define IW_INPUT_STRING_EV		4
#define IW_SET_SCREEN_EV		5
#define IW_PREV_FIGURE_EV		6
#define IW_NEXT_FIGURE_EV		7
#define IW_INIT_ELECTIONARY_EV		8
#define IW_FINIT_ELECTIONARY_EV		9
#define IW_CHOOSE_FIGURE_EV		10
#define IW_INIT_NAME_EV			11
#define IW_INIT_ASSEMBLY_EV		12
#define IW_FINIT_ASSEMBLY_EV		13
#define IW_PREV_PART_EV			14
#define IW_NEXT_PART_EV			15
#define IW_SELECT_PART_TYPE_EV		16
#define IW_BUY_TRACK_EV			17
#define IW_NEXT_PART_TYPE_EV		18
#define IW_PREV_PART_TYPE_EV		19
#define IW_ARCANE_DEMO_EV		20
#define IW_CHECK_NAME_EV		21
#define IW_MOVE_TO_PLACE		22
#define IW_SELECT_FIGURE_EV		23
#define IW_CANCEL_ELECTIONARY_EV	24
#define IW_CANCEL_ASSEMBLY_EV		25
#define IW_KEYTRAP_EV			26
#define IW_TELEPORT_GO_EV		27
#define IW_SET_TURNBASED_EV		28
#define IW_TOGGLE_TURNBASED_EV		29
#define IW_TELEPORT_CANCEL_EV		30
#define IW_DOGGY_EV			31

#define IW_DY0				50
#define IW_Y0				430

