
#define iTXT_WORLD		1
#define iTXT_DROP_CP		4
#define iTXT_TRY_AGAIN		5
#define iTXT_GO_AWAY		6
#define iTXT_LOST		7
#define iTXT_CONTINUE		8
#define iTXT_BONANZA_RACE	9
#define iTXT_WON_SPELL0		10
#define iTXT_WON_SPELL1		11
#define iTXT_WINNER		12
#define iTXT_BUY_SPELL		13
#define iTXT_BUY_IT		14
#define iTXT_NO_THANKS		15
#define iTXT_NOT_ENOUGH		16
#define iTXT_NEXT_TIME		17
#define iTXT_PLAY_AGAIN		18
#define iTXT_PRESS_KEY		19
#define iTXT_WAIT_TURN		20
#define iTXT_TURN		21
#define iTXT_LAP		22
#define iTXT_FINAL_LAP		23
#define iTXT_TURNS		24
#define iTXT_PRICE		25
#define iTXT_COST		26
#define iTXT_NOT_ENOUGH1	27
#define iTXT_TIPS00		28
#define iTXT_TIPS01		29
#define iTXT_TIPS02		30
#define iTXT_TIPS03		31
#define iTXT_TIPS04		32
#define iTXT_TIPS1		33
#define iTXT_CONTACTS		35
#define iTXT_SPELL_NA		36
#define iTXT_WAIT		37
#define iTXT_TB_MODE		38
#define iTXT_RT_MODE		39
#define iTXT_TO_BUY		40
#define iTXT_TRACK_NA1		41
#define iTXT_TRACK_NA2		42
#define iTXT_COME_LATER		43
#define iTXT_PRIZE		44
#define iTXT_MAILTO		45
#define iTXT_CONTINUE_WITH	46
#define iTXT_ENG_LAYOUT		47
#define iTXT_LOCAL_LAYOUT	48
#define iTXT_OTHER_LAYOUT	49
#define iTXT_REPLAY_TURN	50
#define iTXT_NONE		51
#define iTXT_VERSION_ID		52
#define iTXT_OK			53
#define iTXT_WAIT_TURN_FINISHED	54
#define iTXT_REPLAY_GAME	55
#define iTXT_ERROR		56
#define iTXT_CONNECT		57
#define iTXT_SEND		58
#define iTXT_RECEIVE		59
#define iTXT_RETRY		60
#define iTXT_SENT_OK		61
#define iTXT_EDIT_TURN		62
#define iTXT_WAITING_FOR	63
#define iTXT_REFRESH		64
#define iTXT_CHANGE_PLAYER	65
#define iTXT_CHANGE_PLAYER_T	66
#define iTXT_USE_ARROWS		67
#define iTXT_CHANGE_CONTINUE	68
#define iTXT_GAME_TITLE		69
#define iTXT_NAME00		70
#define iTXT_NAME14		84
#define iTXT_PLACE0		85
#define iTXT_PLACE4		89
#define iTXT_LATE_TURN		90
#define iTXT_INTRO_SCENE1	91
#define iTXT_INTRO_SCENE2	92
#define iTXT_INTRO_SCENE3	93
#define iTXT_INTRO_SCENE4	94
#define iTXT_INTRO_SCENE5	95
#define iTXT_INTRO_SCENE6	96
#define iTXT_INTRO_SCENE7	97
#define iTXT_CHAR00		98
#define iTXT_CHAR10		108
#define iTXT_OUTRO		109
#define	iTXT_BAD_PACKET		110
#define iTXT_ONLINE_URL		111
#define iTXT_CDLABEL		112
#define iTXT_NOCD_MSG		113
#define iTXT_EXE_ACTIVE		114
