
#define CDTRACK_TR_DEMO		9
#define CDTRACK_RACE_WON	10
#define CDTRACK_RACE_NOT_LOST	11
#define CDTRACK_RACE_LOST	12
#define CDTRACK_MAIN_MENU	2
#define CDTRACK_CREDITS		13

#define CDTRACK_MAX		23
