KeyID	$FXLAB_ID_KEY_CHECKPOINT0
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_NONE | $FXLAB_KEY_ATTRIBUTE_STORAGE"

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_CHECKPOINT1
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0


	KeyTime	10.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.1

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_CHECKPOINT2
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_CHECKPOINT3
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"


	KeyTime	10.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 2.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_CHECKPOINT4
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0


	KeyTime	10.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData -1.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_CHECKPOINT5
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.1

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0


	KeyTime	10.0

	KeyName	Radius
	KeyData	15.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0

	KeyName	DeltaAngle
	KeyData 10.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}


KeyID	$FXLAB_ID_KEY_POLAR_STAR
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Psi
	KeyDefine	Thetta
	KeyDefine	Radius
	KeyDefine	Phase
	KeyDefine	Alpha
	KeyDefine	Scale

	KeyTime	0.0

	KeyName	Psi
	KeyData	0.0

	KeyName	Thetta
	KeyData 0.0

	KeyName Radius
	KeyData 80.0

	KeyName Phase
	KeyData 0.0

	KeyName Alpha
	KeyData 1.0

	KeyName Scale
	KeyData 1.0


	KeyTime	5.0

	KeyName	Psi
	KeyData	0.0

	KeyName	Thetta
	KeyData "0.5*3.14"

	KeyName Phase
	KeyData 0.9


	KeyTime 15.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	25.0

	KeyName	Psi
	KeyData	"2.0 * 3.14"

	KeyName	Thetta
	KeyData "0.5*3.14"

	KeyName Radius
	KeyData 0.0

	KeyName Phase
	KeyData 1.0

	KeyName Alpha
	KeyData 0.0

	KeyName Scale
	KeyData 0.2
}


//------------

KeyID	$FXLAB_ID_KEY_CHECKPOINT6
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_NONE | $FXLAB_KEY_ATTRIBUTE_STORAGE"

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"
}


KeyID	$FXLAB_ID_KEY_CHECKPOINT7
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase

	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"


	KeyTime	10.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"
}


//----------------------

KeyID	$FXLAB_ID_KEY_CHECKPOINT8
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"


	KeyTime	10.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.5

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0

	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"
}


KeyID	$FXLAB_ID_KEY_CHECKPOINT9
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Radius
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	DeltaAngle
	KeyDefine	MovePhase
	KeyDefine	PhaseDelta
	KeyDefine	PhaseStep

	KeyTime	0.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.5

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 0.0


	KeyName	PhaseDelta
	KeyData	0.05

	KeyName	PhaseStep
	KeyData "0.1*3.14"


	KeyTime	10.0

	KeyName	Radius
	KeyData	20.0

	KeyName Red
	KeyData 1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0

	KeyName	DeltaAngle
	KeyData 0.0

	KeyName	MovePhase
	KeyData 2.0

	KeyName	PhaseDelta
	KeyData	0.0

	KeyName	PhaseStep
	KeyData 0.0
}
