KeyID $FXLAB_ID_KEY_COLOR_CONTROLLER_PASSAGE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	20.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	0.0


	KeyTime	40.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}

//-----------------------------------------

KeyID $FXLAB_ID_KEY_COLOR_CONTROLLER_SKIN
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	180.0

	KeyName Red
	KeyData	1.0


	KeyTime	200.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}

KeyID $FXLAB_ID_KEY_COLOR_CONTROLLER_ISOLATION
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	180.0

	KeyName Blue
	KeyData	1.0


	KeyTime	200.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}

KeyID $FXLAB_ID_KEY_COLOR_CONTROLLER_ARMOR
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	0.3


	KeyTime	180.0

	KeyName Alpha
	KeyData	0.3


	KeyTime	200.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}

KeyID $FXLAB_ID_KEY_COLOR_CONTROLLER_BIO
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	180.0

	KeyName Green
	KeyData	1.0


	KeyTime	200.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}
