KeyID	$FXLAB_ID_KEY_WORM_GREEN_SLIME_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyDefine	DeltaAnimation

	KeyTime	0.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 20.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005


	KeyTime 4.0

	KeyName Alpha
	KeyData 0.5


	KeyTime 40.0

	KeyName Alpha
	KeyData 0.5


	KeyTime	70.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 20.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005
}

KeyID	$FXLAB_ID_KEY_WORM_GREEN_SLIME_CIRCLE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Force
	KeyDefine	Radius
	KeyDefine	MinZ
	KeyDefine	MaxZ

	KeyTime	0.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	10.0

	KeyName MinZ
	KeyData -16.0

	KeyName MaxZ
	KeyData 16.0


	KeyTime	40.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName MinZ
	KeyData -16.0

	KeyName MaxZ
	KeyData 16.0
}

KeyID $FXLAB_ID_KEY_WORM_GREEN_SLIME_BODY
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Model
	KeyData	47.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName	Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0


	KeyTime	40.0

	KeyName	Model
	KeyData	47.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName	Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0
}

//------------------------------------------------


KeyID	$FXLAB_ID_KEY_WORM_YELLOW_SLIME_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyDefine	DeltaAnimation

	KeyTime	0.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 20.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005



	KeyTime 4.0

	KeyName Alpha
	KeyData 0.5


	KeyTime 40.0

	KeyName Alpha
	KeyData 0.5


	KeyTime	70.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 20.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005
}

KeyID	$FXLAB_ID_KEY_WORM_YELLOW_SLIME_CIRCLE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Force
	KeyDefine	Radius
	KeyDefine	MinZ
	KeyDefine	MaxZ

	KeyTime	0.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	10.0

	KeyName MinZ
	KeyData -16.0

	KeyName MaxZ
	KeyData 16.0


	KeyTime	40.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	15.0

	KeyName MinZ
	KeyData -16.0

	KeyName MaxZ
	KeyData 16.0
}

KeyID $FXLAB_ID_KEY_WORM_YELLOW_SLIME_BODY
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Model
	KeyData	48.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName	Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	1.0


	KeyTime	40.0

	KeyName	Model
	KeyData	48.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName	Blue
	KeyData	1.0

	KeyName	Alpha
	KeyData	0.0
}

//----------------------------

KeyID	$FXLAB_ID_KEY_RAGE_SLIME_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyDefine	DeltaAnimation

	KeyTime	0.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.2

	KeyName Blue
	KeyData	0.8

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 75.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005


	KeyTime	3.0

	KeyName	Model
	KeyData	38.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.2

	KeyName Blue
	KeyData	0.8

	KeyName Alpha
	KeyData 0.5


	KeyName Radius
	KeyData 75.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005
}

KeyID	$FXLAB_ID_KEY_RAGE_SLIME_CIRCLE
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"

	KeyDefine	Force
	KeyDefine	Radius
	KeyDefine	MinZ
	KeyDefine	MaxZ

	KeyTime	0.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	35.0

	KeyName MinZ
	KeyData -16.0

	KeyName MaxZ
	KeyData 16.0
}

//----------------------------------------------------

KeyID	$FXLAB_ID_KEY_BLUE_SLIME_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_REPEAT

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyDefine	DeltaAnimation

	KeyTime	0.0

	KeyName	Model
	KeyData	36.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.6


	KeyName Radius
	KeyData 200.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005


	KeyTime	100.0

	KeyName Alpha
	KeyData 0.7


	KeyTime	200.0

	KeyName Alpha
	KeyData 0.5


	KeyTime	300.0

	KeyName	Model
	KeyData	36.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.6


	KeyName Radius
	KeyData 200.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005
}

KeyID	$FXLAB_ID_KEY_BLUE_SLIME_CIRCLE
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_STORAGE | $FXLAB_KEY_ATTRIBUTE_REPEAT"

	KeyDefine	Force
	KeyDefine	Radius
	KeyDefine	MinZ
	KeyDefine	MaxZ

	KeyTime	0.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	100.0

	KeyName MinZ
	KeyData -32.0

	KeyName MaxZ
	KeyData 32.0
}


//-----------------------------------------------------

KeyID	$FXLAB_ID_KEY_BLUE_SLIME_LARGE_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_REPEAT

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyDefine	DeltaAnimation

	KeyTime	0.0

	KeyName	Model
	KeyData	36.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.6


	KeyName Radius
	KeyData 300.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005


	KeyTime	100.0

	KeyName Alpha
	KeyData 0.7


	KeyTime	200.0

	KeyName Alpha
	KeyData 0.5


	KeyTime	300.0

	KeyName	Model
	KeyData	36.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.6


	KeyName Radius
	KeyData 300.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyName DeltaAnimation
	KeyData 0.005
}

KeyID	$FXLAB_ID_KEY_BLUE_SLIME_LARGE_CIRCLE
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_STORAGE | $FXLAB_KEY_ATTRIBUTE_REPEAT"

	KeyDefine	Force
	KeyDefine	Radius
	KeyDefine	MinZ
	KeyDefine	MaxZ

	KeyTime	0.0

	KeyName	Force
	KeyData	0.0

	KeyName	Radius
	KeyData	160.0

	KeyName MinZ
	KeyData -32.0

	KeyName MaxZ
	KeyData 32.0
}
