KeyID	$FXLAB_ID_KEY_PRIMARY_MASS_SHIFTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Rate
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Rate
	KeyData	0.5

	KeyName	Radius
	KeyData 20.0


	KeyTime	20.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 50.0
}

KeyID	$FXLAB_ID_KEY_SECONDARY_MASS_SHIFTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Rate
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 50.0


	KeyTime	20.0

	KeyName	Rate
	KeyData	0.5

	KeyName	Radius
	KeyData 20.0
}


KeyID	$FXLAB_ID_KEY_MASS_SHIFTER_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 1.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyTime	10.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0
	
	KeyName Alpha
	KeyData 1.0

	KeyName Radius
	KeyData 80.0


	KeyTime	20.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 80.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}

KeyID	$FXLAB_ID_KEY_MASS_SHIFTER_MODEL_NITRO
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.6

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 1.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyTime	10.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.6

	KeyName Blue
	KeyData	0.0
	
	KeyName Alpha
	KeyData 1.0

	KeyName Radius
	KeyData 80.0


	KeyTime	20.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.6

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 80.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}

//--------------------------

KeyID $FXLAB_ID_KEY_TELEPORT_OMNI
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Red
	KeyData	1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	25.0


	KeyTime	40.0

	KeyName	Red
	KeyData	0.1

	KeyName Green
	KeyData	0.1

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	80.0
}


KeyID $FXLAB_ID_KEY_TELEPORT_OMNI_NITRO
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Red
	KeyData	1.0

	KeyName Green
	KeyData	0.5

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	25.0


	KeyTime	40.0

	KeyName	Red
	KeyData	0.1

	KeyName Green
	KeyData	0.0

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	80.0
}


KeyID	$FXLAB_ID_KEY_SHIFT_TRAP_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	54.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.05


	KeyName Radius
	KeyData 10.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0



	KeyTime	3.0

	KeyName	Model
	KeyData	54.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.5


	KeyName Radius
	KeyData 50.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData "3.14*0.1"
}

KeyID $FLXAB_ID_KEY_SHIFT_TRAP_SPHERE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Radius
	KeyDefine	Height

	KeyTime	0.0

	KeyName	Radius
	KeyData	5.0

	KeyName	Height
	KeyData 1.0


	KeyTime	3.0

	KeyName	Radius
	KeyData	5.0

	KeyName	Height
	KeyData 10.0
}

//---------------------------------------

KeyID $FXLAB_ID_KEY_SERVER_TELEPORT_MENU
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_REPEAT | $FXLAB_KEY_ATTRIBUTE_STORAGE"

	KeyDefine	Power
	KeyDefine	Type
	KeyDefine	ActiveRadius
	KeyDefine	PassiveRadius

	KeyTime	0.0

	KeyName	Power
	KeyData	0.0

	KeyName	Type
	KeyData 0.0

	KeyName	ActiveRadius
	KeyData 50.0

	KeyName	PassiveRadius
	KeyData 50.0
}

//--------------------------

KeyID	$FXLAB_ID_KEY_CORE_TELEPORT_BURN
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	Size
	KeyDefine	Angle
	KeyDefine	Frame


	KeyTime	0.0

	KeyName	Red
	KeyData	0.6

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.2

	KeyName Alpha
	KeyData 1.0

	KeyName	Size
	KeyData	8.0

	KeyName	Angle
	KeyData	0.0

	KeyName	Frame
	KeyData	0.0


	KeyTime	32.0

	KeyName	Red
	KeyData	0.7

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.3

	KeyName Alpha
	KeyData 0.2

	KeyName	Size
	KeyData	8.0

	KeyName	Angle
	KeyData	0.0

	KeyName	Frame
	KeyData	1.0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN_POSITION
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"
	
	KeyDefine	Type
	KeyDefine	DataX
	KeyDefine	DataY
	KeyDefine	DataZ
	KeyDefine	DataA1
	KeyDefine	DataB1
	KeyDefine	DataC1
	KeyDefine	DataA2
	KeyDefine	DataB2
	KeyDefine	DataC2


	KeyTime	0.0

	KeyName	Type
	KeyData	$FXLAB_SWARM_DOMAIN_CIRCLE

	KeyName	DataX
	KeyData	0

	KeyName	DataY
	KeyData	0

	KeyName	DataZ
	KeyData	0

	KeyName	DataA1
	KeyData	30.0

	KeyName	DataB1
	KeyData	40.0

	KeyName	DataC1
	KeyData	0

	KeyName	DataA2
	KeyData	0

	KeyName	DataB2
	KeyData	0

	KeyName	DataC2
	KeyData	0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"
	
	KeyDefine	Type
	KeyDefine	DataX
	KeyDefine	DataY
	KeyDefine	DataZ
	KeyDefine	DataA1
	KeyDefine	DataB1
	KeyDefine	DataC1
	KeyDefine	DataA2
	KeyDefine	DataB2
	KeyDefine	DataC2


	KeyTime	0.0

	KeyName	Type
	KeyData	$FXLAB_SWARM_DOMAIN_LINE

	KeyName	DataX
	KeyData	0

	KeyName	DataY
	KeyData	0

	KeyName	DataZ
	KeyData	0

	KeyName	DataA1
	KeyData	0

	KeyName	DataB1
	KeyData	0

	KeyName	DataC1
	KeyData	10.0

	KeyName	DataA2
	KeyData	0

	KeyName	DataB2
	KeyData	0

	KeyName	DataC2
	KeyData	0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE
	
	KeyDefine	RegenerateTime

	KeyDefine	ImageType
	KeyDefine	ImageID
	KeyDefine	ImageNoise

	KeyDefine	Rate
	KeyDefine	Age
	KeyDefine	StartPower
	KeyDefine	EndPower
	KeyDefine	PositionKeyID
	KeyDefine	VelocityKeyID

	KeyTime	0.0

	KeyName	RegenerateTime
	KeyData	15.0

	KeyName	ImageType
	KeyData	$FXLAB_SCRIPT_SECTION_SPRITE

	KeyName	ImageID
	KeyData	$FXLAB_ID_SPRITE_TELEPORT_BURN

	KeyName	ImageNoise
	KeyData	0


	KeyName	Rate
	KeyData 10.0

	KeyName	Age
	KeyData 20.0

	KeyName	StartPower
	KeyData 0.0

	KeyName	EndPower
	KeyData 1.0

	KeyName	PositionKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_POSITION

	KeyName VelocityKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY


	KeyTime	50.0

	KeyName	RegenerateTime
	KeyData	15.0

	KeyName	ImageType
	KeyData	$FXLAB_SCRIPT_SECTION_SPRITE

	KeyName	ImageID
	KeyData	$FXLAB_ID_SPRITE_TELEPORT_BURN

	KeyName	ImageNoise
	KeyData	0


	KeyName	Rate
	KeyData 5.0

	KeyName	Age
	KeyData 20.0

	KeyName	StartPower
	KeyData 0.0

	KeyName	EndPower
	KeyData 1.0

	KeyName	PositionKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_POSITION

	KeyName VelocityKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY
}


//--------------------------

KeyID	$FXLAB_ID_KEY_CORE_TELEPORT_BURN_LAST
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha
	KeyDefine	Size
	KeyDefine	Angle
	KeyDefine	Frame


	KeyTime	0.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 1.0

	KeyName	Size
	KeyData	16.0

	KeyName	Angle
	KeyData	0.0

	KeyName	Frame
	KeyData	0.0


	KeyTime	32.0

	KeyName	Red
	KeyData	1.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.2

	KeyName	Size
	KeyData	16.0

	KeyName	Angle
	KeyData	"3.14*8.0"

	KeyName	Frame
	KeyData	1.0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN_POSITION_LAST
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"
	
	KeyDefine	Type
	KeyDefine	DataX
	KeyDefine	DataY
	KeyDefine	DataZ
	KeyDefine	DataA1
	KeyDefine	DataB1
	KeyDefine	DataC1
	KeyDefine	DataA2
	KeyDefine	DataB2
	KeyDefine	DataC2


	KeyTime	0.0

	KeyName	Type
	KeyData	$FXLAB_SWARM_DOMAIN_CIRCLE

	KeyName	DataX
	KeyData	0

	KeyName	DataY
	KeyData	0

	KeyName	DataZ
	KeyData	0

	KeyName	DataA1
	KeyData	30.0

	KeyName	DataB1
	KeyData	40.0

	KeyName	DataC1
	KeyData	0

	KeyName	DataA2
	KeyData	0

	KeyName	DataB2
	KeyData	0

	KeyName	DataC2
	KeyData	0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY_LAST
{
	KeyAttribute	"$FXLAB_KEY_ATTRIBUTE_FREEZE | $FXLAB_KEY_ATTRIBUTE_STORAGE"
	
	KeyDefine	Type
	KeyDefine	DataX
	KeyDefine	DataY
	KeyDefine	DataZ
	KeyDefine	DataA1
	KeyDefine	DataB1
	KeyDefine	DataC1
	KeyDefine	DataA2
	KeyDefine	DataB2
	KeyDefine	DataC2


	KeyTime	0.0

	KeyName	Type
	KeyData	$FXLAB_SWARM_DOMAIN_LINE

	KeyName	DataX
	KeyData	0

	KeyName	DataY
	KeyData	0

	KeyName	DataZ
	KeyData	0

	KeyName	DataA1
	KeyData	0

	KeyName	DataB1
	KeyData	0

	KeyName	DataC1
	KeyData	10.0

	KeyName	DataA2
	KeyData	0

	KeyName	DataB2
	KeyData	0

	KeyName	DataC2
	KeyData	0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_BURN_LAST
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_REPEAT
	
	KeyDefine	RegenerateTime

	KeyDefine	ImageType
	KeyDefine	ImageID
	KeyDefine	ImageNoise

	KeyDefine	Rate
	KeyDefine	Age
	KeyDefine	StartPower
	KeyDefine	EndPower
	KeyDefine	PositionKeyID
	KeyDefine	VelocityKeyID

	KeyTime	0.0

	KeyName	RegenerateTime
	KeyData	15.0

	KeyName	ImageType
	KeyData	$FXLAB_SCRIPT_SECTION_SPRITE

	KeyName	ImageID
	KeyData	$FXLAB_ID_SPRITE_TELEPORT_BURN_LAST

	KeyName	ImageNoise
	KeyData	0


	KeyName	Rate
	KeyData 10.0

	KeyName	Age
	KeyData 20.0

	KeyName	StartPower
	KeyData 0.0

	KeyName	EndPower
	KeyData 1.0

	KeyName	PositionKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_POSITION_LAST

	KeyName VelocityKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY_LAST


	KeyTime	50.0

	KeyName	RegenerateTime
	KeyData	15.0

	KeyName	ImageType
	KeyData	$FXLAB_SCRIPT_SECTION_SPRITE

	KeyName	ImageID
	KeyData	$FXLAB_ID_SPRITE_TELEPORT_BURN_LAST

	KeyName	ImageNoise
	KeyData	0


	KeyName	Rate
	KeyData 1.0

	KeyName	Age
	KeyData 20.0

	KeyName	StartPower
	KeyData 0.0

	KeyName	EndPower
	KeyData 1.0

	KeyName	PositionKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_POSITION_LAST

	KeyName VelocityKeyID
	KeyData $FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY_LAST
}

//-------------

KeyID $FXLAB_ID_KEY_MENU_TELEPORT_OMNI
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName Green
	KeyData	0.0

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	5.0


	KeyTime 10.0

	KeyName Red
	KeyData 0.45

	KeyName Green
	KeyData 0.45

	KeyName Radius
	KeyData 80.0
	

	KeyTime	20.0

	KeyName	Red
	KeyData	0.0

	KeyName Green
	KeyData	0.0

	KeyName Blue
	KeyData 0.0

	KeyName Radius
	KeyData	5.0
}

KeyID	$FXLAB_ID_KEY_MENU_TELEPORT_COLOR_CONTROLLER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine   Blue
	KeyDefine	Alpha

	KeyTime	0.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 1.0


	KeyTime	10.0

	KeyName	Red
	KeyData	0.4

	KeyName	Green
	KeyData	0.4

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	0.6


	KeyTime	20.0

	KeyName	Red
	KeyData	0.0

	KeyName	Green
	KeyData	0.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData	1.0
}

KeyID	$FXLAB_ID_KEY_TELEPORT_MENU_ACTIVE_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.05


	KeyName Radius
	KeyData 10.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0



	KeyTime	30.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.75


	KeyName Radius
	KeyData 76.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData "3.14*0.1"
}

KeyID	$FXLAB_ID_KEY_TELEPORT_MENU_PASSIVE_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.05


	KeyName Radius
	KeyData 10.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0



	KeyTime	30.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.75


	KeyName Radius
	KeyData 76.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}

//-----------------------------------

KeyID	$FXLAB_ID_KEY_PRIMARY_MASS_SHIFTER_CHARACTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Rate
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Rate
	KeyData	0.5

	KeyName	Radius
	KeyData 20.0


	KeyTime	20.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 30.0
}

KeyID	$FXLAB_ID_KEY_SECONDARY_MASS_SHIFTER_CHARACTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Rate
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 30.0


	KeyTime	20.0

	KeyName	Rate
	KeyData	0.5

	KeyName	Radius
	KeyData 20.0
}

KeyID	$FXLAB_ID_KEY_MASS_SHIFTER_MODEL_CHARACTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 1.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyTime	10.0

	KeyName Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0
	
	KeyName Alpha
	KeyData 1.0

	KeyName Radius
	KeyData 40.0


	KeyTime	20.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	0.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 50.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}


KeyID $FXLAB_ID_KEY_TELEPORT_OMNI_CHARACTER
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Red
	KeyData	1.0

	KeyName Green
	KeyData	1.0

	KeyName Blue
	KeyData 1.0

	KeyName Radius
	KeyData	25.0


	KeyTime	40.0

	KeyName	Red
	KeyData	0.1

	KeyName Green
	KeyData	0.1

	KeyName Blue
	KeyData 0.1

	KeyName Radius
	KeyData	60.0
}

//----------------------

KeyID	$FXLAB_ID_KEY_MASS_SHIFTER_MOVIE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Rate
	KeyDefine	Radius

	KeyTime	0.0

	KeyName	Rate
	KeyData	0.5

	KeyName	Radius
	KeyData 20.0


	KeyTime	20.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 30.0


	KeyTime	30.0

	KeyName	Rate
	KeyData	3.0

	KeyName	Radius
	KeyData 100.0
}


KeyID	$FXLAB_ID_KEY_MASS_SHIFTER_MODEL_MOVIE
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_NONE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 1.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0


	KeyTime	10.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0
	
	KeyName Alpha
	KeyData 1.0

	KeyName Radius
	KeyData 80.0


	KeyTime	20.0

	KeyName	Model
	KeyData	55.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	0.0

	KeyName Alpha
	KeyData 0.0


	KeyName Radius
	KeyData 80.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}

//------------------------------------------

KeyID	$FXLAB_ID_KEY_TELEPORT_MOVIE_MODEL
{
	KeyAttribute	$FXLAB_KEY_ATTRIBUTE_FREEZE

	KeyDefine	Model
	KeyDefine	Red
	KeyDefine	Green
	KeyDefine	Blue
	KeyDefine	Alpha

	KeyDefine	Radius
	KeyDefine	AngleX
	KeyDefine	AngleY
	KeyDefine	AngleZ

	KeyTime	0.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	1.0

	KeyName	Green
	KeyData	1.0

	KeyName Blue
	KeyData	1.0

	KeyName Alpha
	KeyData 0.05


	KeyName Radius
	KeyData 80.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData "3.14*0.2"


	KeyTime	20.0

	KeyName	Model
	KeyData	74.0

	KeyName Red
	KeyData	0.5

	KeyName	Green
	KeyData	0.5

	KeyName Blue
	KeyData	0.5

	KeyName Alpha
	KeyData 0.75


	KeyName Radius
	KeyData 80.0

	KeyName AngleX
	KeyData 0.0

	KeyName AngleY
	KeyData	0.0

	KeyName AngleZ
	KeyData 0.0
}

