
// aciScreenResource::type values...
#define ACS_NONE	0
#define ACS_BMP 	1
#define ACS_BML 	2
#define ACS_BMO 	3
#define ACS_XBM 	4
#define ACS_PAL 	5
#define ACS_HBM 	6

#define ACS_BUILD_RESOURCE	0x04

// aciScreenObject:type values...
#define ACS_BASE_OBJ		0x01
#define ACS_INPUT_FIELD_OBJ	0x02
#define ACS_SCROLLER_OBJ	0x03

#define MCH_SINGLE_GAME 	2
#define MCH_SPLIT_CONTROL_HS	3
#define MCH_ENTIRE_CONTROL_HS	4

