
// Script keyword IDs...
#define ASCR_POS_X		1
#define ASCR_POS_Y		2

#define ASCR_RESOURCE		3
#define ASCR_TYPE		4
#define ASCR_FILE_NAME		5

#define ASCR_KEY_OBJ		6
#define ASCR_CODE		7
#define ASCR_OPT_CODE		8

#define ASCR_EV_COMMAND 	9
#define ASCR_EV_COMM_DATA	10

#define ASCR_EVENT		11
#define ASCR_TIME		12

#define ASCR_FRAME_SEQ		13
#define ASCR_ID 		14
#define ASCR_RES_ID		15
#define ASCR_FON_RES_ID		16
#define ASCR_START_TIME 	17
#define ASCR_END_TIME		18
#define ASCR_DELTA		19

// aciScreenObject...
#define ASCR_OBJECT		20
#define ASCR_SIZE_X		21
#define ASCR_SIZE_Y		22
#define ASCR_DEFAULT_RES	23
#define ASCR_CUR_FRAME		24
#define ASCR_OBJ_INDEX		25  
#define ASCR_ALIGN_X		26  
#define ASCR_ALIGN_Y		27  

// aciScreenInputField...
#define ASCR_STRING		28
#define ASCR_COLOR0		29
#define ASCR_COLOR1		30
#define ASCR_COLOR2		31
#define ASCR_FONT		32
#define ASCR_SPACE		33
#define ASCR_MAX_STATE		34
#define ASCR_CUR_STATE		35
#define ASCR_STATE_STR		36

// aciScreenScroller...
#define ASCR_CUR_VALUE		37
#define ASCR_MAX_VALUE		38

#define ASCR_FLAG		39

// aciScreen
#define ASCR_SCREEN		40
#define ASCR_NEXT_SCREEN	41
#define ASCR_PREV_SCREEN	42

// Parameters...
#define ASCR_FONTS_DIR		43
#define ASCR_FONTS_PREFIX	44
#define ASCR_FONTS_NUM		45

#define ASCR_PALETTE_ID 	46

#define ASCR_STR_LEN		47

// Alpha
#define ASCR_ALPHA0		48
#define ASCR_ALPHA1		49
#define ASCR_ALPHA2		50
#define ASCR_D_ALPHA		51

// Arcane interface...
#define ARC_SCR_SYMBOL		1000
#define ARC_SCR_CRITICAL	1001

// AI Arcanes
#define ARC_PRM			1002
#define ARC_PRM_DATA		1003

// SpriteDispatcher
#define SPRD_SLOT		2000
#define SPRD_SPRITE		2001

// Doggy
#define IW_DOGGY_PHRASE			3000
#define IW_DOGGY_PHRASE_PRIORITY	3001

// iTexts
#define ASCR_iTEXT		3002
