//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript declaration
//	Section: CameraPrm
//	Number of variables: 87
//	This is computer generated code, don't try to change it
//////////////////////////////////////////////////////////////////////////////////////////////
extern float fCamera;
extern int camera_integration_steps;
extern float camera_distance_min;
extern int enable_zoom_by_wheel;
extern float camera_mouse_wheel_sensitivity;
extern float camera_zoom_sensitivity;
extern float camera_slope_mass_inv;
extern float camera_water_slope_mass_inv;
extern float camera_turn_mass_inv;
extern float camera_distance_mass_inv;
extern float camera_centering_mass_inv;
extern float camera_const_input_mass_inv;
extern float camera_damping_factor;
extern float camera_position_mass_inv_cliped;
extern float camera_slope_mass_inv_cliped_up;
extern float camera_slope_mass_inv_cliped_down;
extern float camera_turn_mass_inv_cliped;
extern float camera_distance_mass_inv_cliped;
extern float camera_damping_factor_cliped;
extern int camera_setMode_interpolation_time;
extern int camera_runStartTimeScenario_interpolation_time;
extern int camera_setObserver_interpolation_time;
extern int camera_enable_clipping;
extern int camera_enable_static_objects_clipping;
extern int camera_enable_gears_clipping;
extern float camera_angle_step;
extern int from_desired_search_attempts;
extern float camera_theta_dominance;
extern float camera_transparensy_distance;
extern float camera_transparensy_power;
extern float clip_ray_radius;
extern float clip_ray_t_min;
extern float S2G_clip_ray_radius;
extern float camera_scroll_damping_factor;
extern float camera_scroll_force_of_distance;
extern float camera_scroll_mass_inv;
extern float camera_fly_stop_time_scale_x;
extern float camera_fly_stop_time_scale_y;
extern float camera_scroll_move_of_distance;
extern float camera_scroll_move_max;
extern float centering_delta_default;
extern float centering_delta_max;
extern float spot_acc_time;
extern float spot_acc_front;
extern float fly_slope;
extern float zoom_by_speed;
extern float zoom_by_speed_velocity_max;
extern float start_scenario_slope0;
extern float start_scenario_distance0;
extern int start_scenario_time1;
extern int start_scenario_time2;
extern float finish_fly_angle_increment;
extern float track_fly_z_offset;
extern int track_fly_enable_binary_search;
extern float track_fly_distance;
extern float track_fly_increment_initial;
extern float track_fly_increment_epsilon;
extern float track_fly_increment;
extern int rotation_when_stop_time_time;
extern float rotation_when_stop_time_speed;
extern float stop_time_z_offset;
extern float stop_time_dxy;
extern float stop_time_max_step;
extern float stop_time_precision;
extern int stop_time_max_iterations;
extern float stop_time_hCamera;
extern float stop_time_share_radius_factor;
extern float free_fly_body_radius;
extern float free_fly_max_climb_angle;
extern float free_fly_roll_angle_decrement_factor;
extern int camera_new_clip;
extern int camera_new_clip_reuse_clipping_number;
extern int camera_new_clip_x_size;
extern int camera_new_clip_y_size;
extern int camera_new_clip_average_distance;
extern float camera_z_buffer_x_dominance;
extern float camera_z_buffer_delta_z;
extern float camera_z_buffer_z_min;
extern float MAX_SLOPE_ANGLE;
extern float SCAN_X_MAX;
extern float camera_min_slope_angle_to_change_psi;
extern float camera_clip_delta_origin;
extern float camera_clip_delta_final;
extern float camera_clip_distance_delta;
extern float camera_clip_distance_factor;
extern float static_observer_rotation_speed;
extern float camera_turn_angle_delta;
//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript end: CameraPrm
//////////////////////////////////////////////////////////////////////////////////////////////
