//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript definition
//	Section: MechosPrm
//	Number of variables: 167
//	This is computer generated code, don't try to change it
//////////////////////////////////////////////////////////////////////////////////////////////
float moment_of_inertia_XY_scaling_factor = 2.f;
float moment_of_inertia_Z_scaling_factor = 2.f;
float mechos_k_restitution_plus_one = 1.25f;
float mechos_obstacle_slope_z = 0.6f;
float horizontal_ellipsoid_factor = 1.5f;
float horizontal_Ig_inv_z_factor = 1.f;
float horizontal_k_restitution_plus_one = 1.4f;
float horizontal_velocity_relaxation_value = 1.e-002f;
float mechos_collision_correction_restitution = 0.f;
int enable_vertical_analytics = 0;
float vertical_velocity_relaxation_value = 5.f;
float mechos_diagonal_element_scaling_factor = 1.1f;
float mechos_penalty_force_max = 300.f;
float mechos_tangent_velocity_min = 1.e-003f;
float mechos_free_brake_damping = 5.e-002f;
float mechos_free_brake_torque = 5.e-002f;
float low_gear_velocity_threshould = 7.f;
float low_gear_traction = 1.5f;
float mechos_general_base_y = 25.f;
float mechos_rudder_speed_decrease_factor_bot = 2.e-002f;
int mechos_obstacle_rudder_enabled = 1;
float max_rudder_angle_obstacle = 1.f;
float mechos_obstacle_rudder_velocity_threshould = 10.f;
float mechos_obstacle_rudder_pitch_threshould = 60.f;
float mechos_obstacle_rudder_t_factor = 10.f;
float mechos_obstacle_rudder_t_avr_tau = 1.e-002f;
float mechos_obstacle_rudder_t_backward_wheel_start_threshould = 0.5f;
float mechos_dragV_free = 0.f;
float mechos_dragW_free = 1.e-002f;
float mechos_speed_bound_drag = 0.1f;
float mechos_buoyancy = 0.15f;
float k_rudder_water = 1.2f;
float k_traction_water = 8.f;
float mechos_water_brake_damping = 0.7f;
float mechos_swing_lift_force = 5.f;
float mechos_swing_torque = 1.f;
float mechos_swing_phase = 1.8f;
float Vx_max_mechos = 8.f;
float Wz_max_mechos = 1.2f;
float V_brake_max = 30.f;
float rudder_force_max_mechos = 25.f;
float dust_speed_factor = 1.25e-002f;
float personage_rudder = 0.4f;
float personage_traction = 10.f;
float personage_buoyancy = 0.15f;
float standing_personage_manual_rudder = 0.5f;
float standing_personage_automatic_rudder = 0.8f;
float character_angle_x_mass_inv = 0.6f;
float character_angle_y_mass_inv = 0.6f;
float character_angle_x_factor = 1.f;
float character_angle_y_factor = 2.f;
float character_angle_x_spot_acceleration = 2.f;
float character_angle_x_min = -0.7f;
float character_angle_x_max = 1.f;
float character_angle_y_max = 0.79f;
float collision_effect_velocity_threshould = 30.f;
float stone_hit_effect_velocity_threshould = 5.f;
float frozen_mechos_hit_velocity_threshould = 20.f;
float hit_sound_velocity_threshould = 15.f;
float mechos_upper_hit_velocity_threshould = 15.f;
float mechos_upper_hit_theta_threshould = 0.7f;
float mechos_hit_velocity2sound_factor = 5.e-002f;
float terrain_hit_velocity2sound_factor = 5.e-002f;
float terrain_wheels_hit_velocity2sound_factor = 5.e-002f;
float mechos_wheels_sound_frequency_factor = 4.e-002f;
float mechos_sound_factor_low_threshould = -0.8f;
int mechos_engine_sound_on_delay = 100;
int mechos_engine_sound_off_delay = 100;
float animal_obstacle_turns = 1.f;
float animal_obstacle_rotation_speed = 2.f;
float animal_obstacle_vertical_velocity = 60.f;
float animal_obstacle_immunity_time = 5000.f;
float slime_obstacle_turns = 1.f;
float slime_obstacle_rotation_speed = 2.f;
float slime_obstacle_horizontal_velocity = 20.f;
float slime_obstacle_immunity_time = 5000.f;
float kinetic_impulse_rotation_speed = 3.f;
float kinetic_impulse_distance = 700.f;
float kinetic_impulse_vertical_velocity = 40.f;
float mechos_trail_dz = 2.f;
float mechos_trail_length = 10.f;
float mechos_trail_time = 5000.f;
float mechos_trail_started_time = 50.f;
float ordinaryTrail[4] = { 0.f 
 , 0.f, 0.f, 0.5f };
float snowTrail[4] = { 1.f, 1.f, 1.f, 0.5f };
float redSlimeTrail[4] = { 0.25f 
 , 5.e-002f, 0.15f, 0.5f };
float greenSlimeTrail[4] = { 0.f, 0.5f, 0.f, 0.5f };
float yellowSlimeTrail[4] = { 0.25f 
 , 0.5f, 0.f, 0.5f };
float blueSlimeTrail[4] = { 0.1f, 0.2f, 0.5f, 0.5f };
float redTrackTrail[4] = { 1.f 
 , 0.2f, 0.f, 0.8f };
int main_period = 2000;
int exult_period = 2000;
int sadness_period = 3000;
int outstrip_period = 2000;
int hit_period = 200;
int run_period = 700;
int resting_disturb_random_delay = 8000;
int hit_delay = 5000;
float assembling_point_dist_eps = 0.5f;
float choose_teleportation_distance_xy_threshould = 300.f;
float choose_teleportation_distance_z_threshould = 50.f;
float choose_teleportation_time_threshould = 1000.f;
float waiting_for_teleportation_time = 1000.f;
float starting_teleportation_time = 1000.f;
float finishing_teleportation_time = 1000.f;
float teleportation_size = 2.f;
float teleportation_spin = 6.f;
float teleportation_spin_initial = 0.8f;
float teleportation_psi_error = 0.8f;
float catch_width_general = 60.f;
float catch_length_general = 30.f;
float allowed_width_general = 25.f;
float k_distance_to_traction = 3.2e-003f;
float back_moving_ymax = 71.f;
float back_moving_kmax = 0.989962f;
float backward_maneuver_threshold = 5.e-002f;
float front_moving_kmax = 1.f;
float curvature_factor = 300.f;
float brake_lower_speed = 25.f;
float brake_upper_speed = 50.f;
float rudder_step = 0.1f;
float min_relative_curvature = 0.8f;
float max_relative_curvature = 1.2f;
float curvature_denominator_anti_singular_addition = 6.f;
float traction_avr_zero = 0.25f;
float traction_avr_tau = 7.5e-003f;
float velocity_y_avr_zero = 2.f;
float velocity_y_avr_tau = 0.1f;
int backward_maneuver_obstacle_timer_duration = 800;
int backward_maneuver_velocity_timer_duration = 2000;
int backward_maneuver_duration = 1500;
int control_point_approach_duration = 6000;
float control_point_approach_epsilon = 0.5f;
float obstacle_avr_tau = 0.1f;
float obstacle_avr_threshould = 0.4f;
float part_link_force = 3.f;
float part_buoyancy = 0.15f;
float part_dragV = 0.5f;
float part_dragW = 0.5f;
float part_dragW_formic = 1.5f;
float part_V = 15.f;
float part_W = 1.f;
float part_lift_force_factor = 1.2f;
float part_forced_moving_lift_force_factor = 2.f;
float part_forced_moving_distance = 5.f;
float part_colliding_duration = 50.f;
int part_stopping_detection_delay = 3000;
float part_merge_distance = 20.f;
int disorganize_duration = 1000;
float part_swing_lift_force = 5.f;
float part_swing_torque = 1.f;
float mechos_teleportation_time = 1000.f;
float mechos_teleportation_rotation = 4.e-002f;
float mechos_teleportation_z_offset = 30.f;
float upper_direction_penetration_max = 25.f;
float lower_direction_penetration_max = 7.f;
float horizontal_direction_penetration_max = 10.f;
float mechos_skidding_factor = 2.5e-002f;
float mechos_skidding_avr_tau = 5.e-002f;
float mechos_skidding_factor_sound_threshould = 1.f;
int mechos_skidding_sound_on_delay = 50;
int mechos_skidding_sound_pause = 600;
float acceleration_chance_time = 200.f;
float jump_velocity_y = 50.f;
float jump_velocity_z = 100.f;
int allow_transparency_of_bridges = 1;
int parts_collision_flags = 0;

#ifdef _PRM_EDIT_
struct MechosPrm_ParameterSection : ParameterSection
{
	MechosPrm_ParameterSection() : ParameterSection("MechosPrm")
{
	add_dependency("Scripts/Xreal/Mechos.prm");
	sourceCRC = 1404113363;
	description = 757107422;
	reserve(167);
	add(&moment_of_inertia_XY_scaling_factor, "moment_of_inertia_XY_scaling_factor");
	add(&moment_of_inertia_Z_scaling_factor, "moment_of_inertia_Z_scaling_factor");
	add(&mechos_k_restitution_plus_one, "mechos_k_restitution_plus_one");
	add(&mechos_obstacle_slope_z, "mechos_obstacle_slope_z");
	add(&horizontal_ellipsoid_factor, "horizontal_ellipsoid_factor");
	add(&horizontal_Ig_inv_z_factor, "horizontal_Ig_inv_z_factor");
	add(&horizontal_k_restitution_plus_one, "horizontal_k_restitution_plus_one");
	add(&horizontal_velocity_relaxation_value, "horizontal_velocity_relaxation_value");
	add(&mechos_collision_correction_restitution, "mechos_collision_correction_restitution");
	add(&enable_vertical_analytics, "enable_vertical_analytics");
	add(&vertical_velocity_relaxation_value, "vertical_velocity_relaxation_value");
	add(&mechos_diagonal_element_scaling_factor, "mechos_diagonal_element_scaling_factor");
	add(&mechos_penalty_force_max, "mechos_penalty_force_max");
	add(&mechos_tangent_velocity_min, "mechos_tangent_velocity_min");
	add(&mechos_free_brake_damping, "mechos_free_brake_damping");
	add(&mechos_free_brake_torque, "mechos_free_brake_torque");
	add(&low_gear_velocity_threshould, "low_gear_velocity_threshould");
	add(&low_gear_traction, "low_gear_traction");
	add(&mechos_general_base_y, "mechos_general_base_y");
	add(&mechos_rudder_speed_decrease_factor_bot, "mechos_rudder_speed_decrease_factor_bot");
	add(&mechos_obstacle_rudder_enabled, "mechos_obstacle_rudder_enabled");
	add(&max_rudder_angle_obstacle, "max_rudder_angle_obstacle");
	add(&mechos_obstacle_rudder_velocity_threshould, "mechos_obstacle_rudder_velocity_threshould");
	add(&mechos_obstacle_rudder_pitch_threshould, "mechos_obstacle_rudder_pitch_threshould");
	add(&mechos_obstacle_rudder_t_factor, "mechos_obstacle_rudder_t_factor");
	add(&mechos_obstacle_rudder_t_avr_tau, "mechos_obstacle_rudder_t_avr_tau");
	add(&mechos_obstacle_rudder_t_backward_wheel_start_threshould, "mechos_obstacle_rudder_t_backward_wheel_start_threshould");
	add(&mechos_dragV_free, "mechos_dragV_free");
	add(&mechos_dragW_free, "mechos_dragW_free");
	add(&mechos_speed_bound_drag, "mechos_speed_bound_drag");
	add(&mechos_buoyancy, "mechos_buoyancy");
	add(&k_rudder_water, "k_rudder_water");
	add(&k_traction_water, "k_traction_water");
	add(&mechos_water_brake_damping, "mechos_water_brake_damping");
	add(&mechos_swing_lift_force, "mechos_swing_lift_force");
	add(&mechos_swing_torque, "mechos_swing_torque");
	add(&mechos_swing_phase, "mechos_swing_phase");
	add(&Vx_max_mechos, "Vx_max_mechos");
	add(&Wz_max_mechos, "Wz_max_mechos");
	add(&V_brake_max, "V_brake_max");
	add(&rudder_force_max_mechos, "rudder_force_max_mechos");
	add(&dust_speed_factor, "dust_speed_factor");
	add(&personage_rudder, "personage_rudder");
	add(&personage_traction, "personage_traction");
	add(&personage_buoyancy, "personage_buoyancy");
	add(&standing_personage_manual_rudder, "standing_personage_manual_rudder");
	add(&standing_personage_automatic_rudder, "standing_personage_automatic_rudder");
	add(&character_angle_x_mass_inv, "character_angle_x_mass_inv");
	add(&character_angle_y_mass_inv, "character_angle_y_mass_inv");
	add(&character_angle_x_factor, "character_angle_x_factor");
	add(&character_angle_y_factor, "character_angle_y_factor");
	add(&character_angle_x_spot_acceleration, "character_angle_x_spot_acceleration");
	add(&character_angle_x_min, "character_angle_x_min");
	add(&character_angle_x_max, "character_angle_x_max");
	add(&character_angle_y_max, "character_angle_y_max");
	add(&collision_effect_velocity_threshould, "collision_effect_velocity_threshould");
	add(&stone_hit_effect_velocity_threshould, "stone_hit_effect_velocity_threshould");
	add(&frozen_mechos_hit_velocity_threshould, "frozen_mechos_hit_velocity_threshould");
	add(&hit_sound_velocity_threshould, "hit_sound_velocity_threshould");
	add(&mechos_upper_hit_velocity_threshould, "mechos_upper_hit_velocity_threshould");
	add(&mechos_upper_hit_theta_threshould, "mechos_upper_hit_theta_threshould");
	add(&mechos_hit_velocity2sound_factor, "mechos_hit_velocity2sound_factor");
	add(&terrain_hit_velocity2sound_factor, "terrain_hit_velocity2sound_factor");
	add(&terrain_wheels_hit_velocity2sound_factor, "terrain_wheels_hit_velocity2sound_factor");
	add(&mechos_wheels_sound_frequency_factor, "mechos_wheels_sound_frequency_factor");
	add(&mechos_sound_factor_low_threshould, "mechos_sound_factor_low_threshould");
	add(&mechos_engine_sound_on_delay, "mechos_engine_sound_on_delay");
	add(&mechos_engine_sound_off_delay, "mechos_engine_sound_off_delay");
	add(&animal_obstacle_turns, "animal_obstacle_turns");
	add(&animal_obstacle_rotation_speed, "animal_obstacle_rotation_speed");
	add(&animal_obstacle_vertical_velocity, "animal_obstacle_vertical_velocity");
	add(&animal_obstacle_immunity_time, "animal_obstacle_immunity_time");
	add(&slime_obstacle_turns, "slime_obstacle_turns");
	add(&slime_obstacle_rotation_speed, "slime_obstacle_rotation_speed");
	add(&slime_obstacle_horizontal_velocity, "slime_obstacle_horizontal_velocity");
	add(&slime_obstacle_immunity_time, "slime_obstacle_immunity_time");
	add(&kinetic_impulse_rotation_speed, "kinetic_impulse_rotation_speed");
	add(&kinetic_impulse_distance, "kinetic_impulse_distance");
	add(&kinetic_impulse_vertical_velocity, "kinetic_impulse_vertical_velocity");
	add(&mechos_trail_dz, "mechos_trail_dz");
	add(&mechos_trail_length, "mechos_trail_length");
	add(&mechos_trail_time, "mechos_trail_time");
	add(&mechos_trail_started_time, "mechos_trail_started_time");
	add(&ordinaryTrail, "ordinaryTrail");
	add(&snowTrail, "snowTrail");
	add(&redSlimeTrail, "redSlimeTrail");
	add(&greenSlimeTrail, "greenSlimeTrail");
	add(&yellowSlimeTrail, "yellowSlimeTrail");
	add(&blueSlimeTrail, "blueSlimeTrail");
	add(&redTrackTrail, "redTrackTrail");
	add(&main_period, "main_period");
	add(&exult_period, "exult_period");
	add(&sadness_period, "sadness_period");
	add(&outstrip_period, "outstrip_period");
	add(&hit_period, "hit_period");
	add(&run_period, "run_period");
	add(&resting_disturb_random_delay, "resting_disturb_random_delay");
	add(&hit_delay, "hit_delay");
	add(&assembling_point_dist_eps, "assembling_point_dist_eps");
	add(&choose_teleportation_distance_xy_threshould, "choose_teleportation_distance_xy_threshould");
	add(&choose_teleportation_distance_z_threshould, "choose_teleportation_distance_z_threshould");
	add(&choose_teleportation_time_threshould, "choose_teleportation_time_threshould");
	add(&waiting_for_teleportation_time, "waiting_for_teleportation_time");
	add(&starting_teleportation_time, "starting_teleportation_time");
	add(&finishing_teleportation_time, "finishing_teleportation_time");
	add(&teleportation_size, "teleportation_size");
	add(&teleportation_spin, "teleportation_spin");
	add(&teleportation_spin_initial, "teleportation_spin_initial");
	add(&teleportation_psi_error, "teleportation_psi_error");
	add(&catch_width_general, "catch_width_general");
	add(&catch_length_general, "catch_length_general");
	add(&allowed_width_general, "allowed_width_general");
	add(&k_distance_to_traction, "k_distance_to_traction");
	add(&back_moving_ymax, "back_moving_ymax");
	add(&back_moving_kmax, "back_moving_kmax");
	add(&backward_maneuver_threshold, "backward_maneuver_threshold");
	add(&front_moving_kmax, "front_moving_kmax");
	add(&curvature_factor, "curvature_factor");
	add(&brake_lower_speed, "brake_lower_speed");
	add(&brake_upper_speed, "brake_upper_speed");
	add(&rudder_step, "rudder_step");
	add(&min_relative_curvature, "min_relative_curvature");
	add(&max_relative_curvature, "max_relative_curvature");
	add(&curvature_denominator_anti_singular_addition, "curvature_denominator_anti_singular_addition");
	add(&traction_avr_zero, "traction_avr_zero");
	add(&traction_avr_tau, "traction_avr_tau");
	add(&velocity_y_avr_zero, "velocity_y_avr_zero");
	add(&velocity_y_avr_tau, "velocity_y_avr_tau");
	add(&backward_maneuver_obstacle_timer_duration, "backward_maneuver_obstacle_timer_duration");
	add(&backward_maneuver_velocity_timer_duration, "backward_maneuver_velocity_timer_duration");
	add(&backward_maneuver_duration, "backward_maneuver_duration");
	add(&control_point_approach_duration, "control_point_approach_duration");
	add(&control_point_approach_epsilon, "control_point_approach_epsilon");
	add(&obstacle_avr_tau, "obstacle_avr_tau");
	add(&obstacle_avr_threshould, "obstacle_avr_threshould");
	add(&part_link_force, "part_link_force");
	add(&part_buoyancy, "part_buoyancy");
	add(&part_dragV, "part_dragV");
	add(&part_dragW, "part_dragW");
	add(&part_dragW_formic, "part_dragW_formic");
	add(&part_V, "part_V");
	add(&part_W, "part_W");
	add(&part_lift_force_factor, "part_lift_force_factor");
	add(&part_forced_moving_lift_force_factor, "part_forced_moving_lift_force_factor");
	add(&part_forced_moving_distance, "part_forced_moving_distance");
	add(&part_colliding_duration, "part_colliding_duration");
	add(&part_stopping_detection_delay, "part_stopping_detection_delay");
	add(&part_merge_distance, "part_merge_distance");
	add(&disorganize_duration, "disorganize_duration");
	add(&part_swing_lift_force, "part_swing_lift_force");
	add(&part_swing_torque, "part_swing_torque");
	add(&mechos_teleportation_time, "mechos_teleportation_time");
	add(&mechos_teleportation_rotation, "mechos_teleportation_rotation");
	add(&mechos_teleportation_z_offset, "mechos_teleportation_z_offset");
	add(&upper_direction_penetration_max, "upper_direction_penetration_max");
	add(&lower_direction_penetration_max, "lower_direction_penetration_max");
	add(&horizontal_direction_penetration_max, "horizontal_direction_penetration_max");
	add(&mechos_skidding_factor, "mechos_skidding_factor");
	add(&mechos_skidding_avr_tau, "mechos_skidding_avr_tau");
	add(&mechos_skidding_factor_sound_threshould, "mechos_skidding_factor_sound_threshould");
	add(&mechos_skidding_sound_on_delay, "mechos_skidding_sound_on_delay");
	add(&mechos_skidding_sound_pause, "mechos_skidding_sound_pause");
	add(&acceleration_chance_time, "acceleration_chance_time");
	add(&jump_velocity_y, "jump_velocity_y");
	add(&jump_velocity_z, "jump_velocity_z");
	add(&allow_transparency_of_bridges, "allow_transparency_of_bridges");
	add(&parts_collision_flags, "parts_collision_flags");
	add_parameter_section(this);
}
};
static MechosPrm_ParameterSection MechosPrm_ParameterSectionObject;
#endif  //  _PRM_EDIT_
//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript end: MechosPrm
//////////////////////////////////////////////////////////////////////////////////////////////
