//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript definition
//	Section: AnimalArcansPrm
//	Number of variables: 98
//	This is computer generated code, don't try to change it
//////////////////////////////////////////////////////////////////////////////////////////////
int death_by_water_duration = 1000;
float evil_eye_finish_size = 2.f;
int evil_eye_time_to_live = 10000;
int evil_eye_time_to_explode = 5000;
int evil_eye_attack_latency_time = 1000;
int evil_eye_jump_latency_time = 500;
int evil_eye_period = 800;
float evil_eye_joining_z_factor = 1.5f;
float evil_eye_joining_distance_factor = 0.8f;
float evil_eye_velocity_factor = 0.7f;
float evil_eye_delta_z = 100.f;
float evil_eye_attack_distance = 300.f;
float evil_eye_catch_distance = 70.f;
float evil_eye_buoyancy = 0.2f;
int little_spider_flash_period = 1500;
float little_spider_flash_amplitude = 2.f;
int little_spider_time_to_live = 20000;
int bubble_time_to_live = 20000;
int bubble_time_to_grow = 3000;
int bubble_time_to_hold_mechos = 4000;
int bubble_owner_protection_time = 2000;
float bubble_active_size = 0.5f;
float bubble_restitution_plus_one = 1.9f;
float bubble_buoyancy = 1.e-002f;
float bubble_freeHeight = -10.f;
float bubble_cargoHeight = 150.f;
float bubble_freeGravity = 2.f;
float bubble_cargoGravity = 5.f;
float bubble_freeWind = 1.f;
float bubble_cargoWind = 0.25f;
float bubble_field_source_radius_factor = 0.8f;
float bubble_field_z_offset = 0.f;
float bubble_field_force = 2.f;
float bubble_field_damping = 12.f;
int suicide_time_to_live = 60000;
int suicide_time_to_live_interface = 4000;
int suicide_time_to_grow = 1000;
float suicide_traction = 25.f;
float suicide_rudder = 0.7f;
float suicide_dragVx = 5.f;
float suicide_dragVy = 0.2f;
float suicide_dragVz = 0.2f;
float suicide_dragWxy = 0.8f;
float suicide_dragWz = 8.f;
float suicide_bbox_x = 50.f;
float suicide_bbox_y = 50.f;
int suicide_laps = 2;
float suicide_initial_Vy = 60.f;
float suicide_max_distance_to_attack_mechos = 300.f;
float suicide_average_stop_velocity = 20.f;
int suicide_average_stop_delay = 500;
float suicide_impact_velocity = 30.f;
float suicide_impact_normal_y = 0.8f;
float bonus_man_buoyancy = 4.5e-002f;
float bonus_man_submersion_threshould = 0.8f;
float bonus_man_mechos_hit_velocity = 10.f;
int bonus_man_switch_time_threshould = 1000;
float bonus_man_shadow_height_threshould = 80.f;
float bonus_man_beeped_distance = 300.f;
int bonus_man_beeped_time = 4000;
int bonus_man_burning_time = 500;
int static_bonus_birth_delay = 3000;
float beeped_bonus_Vxy = 5.f;
float beeped_bonus_Vz = 30.f;
float beeped_bonus_W = 0.3f;
float meteorite_W = 1.f;
float bonus_meteorite_buoyancy = 0.1f;
float snow_ball_scale_radius = 4.f;
float snow_ball_dragV = 0.5f;
int ball_time_to_live = 5000;
float ball_drag_vw = 5.e-002f;
float ball_initial_V = 40.f;
float ball_initial_W = 1.f;
float ball_buoyancy = 0.2f;
float ball_traction_factor = 0.4f;
float ball_steering_factor = 2.5e-002f;
float ball_max_Vxy = 40.f;
float clown_buoyancy = 5.e-002f;
float tomato_mass = 3.f;
float tomato_TOI_scale = 10.f;
float tomato_radius_scale = 0.8f;
float tomato_linear_damping = 2.f;
float tomato_angular_damping = 4.f;
float tomato_return_force = 0.f;
float tomato_buoyancy = 4.e-002f;
float tomato_swing_lift_force = 10.f;
float tomato_swing_torque = 1.f;
float titanium_ball_damage = 0.f;
float titanium_ball_time_to_grow = 1500.f;
float titanium_ball_time_to_live = 20000.f;
float titanium_ball_restitution_plus_one = 1.12f;
float titanium_ball_mass = 2.f;
float titanium_ball_damping = 0.1f;
float titanium_ball_Vxy = 50.f;
float titanium_ball_Vz = 25.f;
float crystal_max_slope = 0.4f;
float crystal_energy = 2.f;
float crystal_damage_by_mechos = 0.1f;

#ifdef _PRM_EDIT_
struct AnimalArcansPrm_ParameterSection : ParameterSection
{
	AnimalArcansPrm_ParameterSection() : ParameterSection("AnimalArcansPrm")
{
	add_dependency("Scripts/Xreal/AnimalArcans.prm");
	sourceCRC = 1236072287;
	description = 1828768550;
	reserve(98);
	add(&death_by_water_duration, "death_by_water_duration");
	add(&evil_eye_finish_size, "evil_eye_finish_size");
	add(&evil_eye_time_to_live, "evil_eye_time_to_live");
	add(&evil_eye_time_to_explode, "evil_eye_time_to_explode");
	add(&evil_eye_attack_latency_time, "evil_eye_attack_latency_time");
	add(&evil_eye_jump_latency_time, "evil_eye_jump_latency_time");
	add(&evil_eye_period, "evil_eye_period");
	add(&evil_eye_joining_z_factor, "evil_eye_joining_z_factor");
	add(&evil_eye_joining_distance_factor, "evil_eye_joining_distance_factor");
	add(&evil_eye_velocity_factor, "evil_eye_velocity_factor");
	add(&evil_eye_delta_z, "evil_eye_delta_z");
	add(&evil_eye_attack_distance, "evil_eye_attack_distance");
	add(&evil_eye_catch_distance, "evil_eye_catch_distance");
	add(&evil_eye_buoyancy, "evil_eye_buoyancy");
	add(&little_spider_flash_period, "little_spider_flash_period");
	add(&little_spider_flash_amplitude, "little_spider_flash_amplitude");
	add(&little_spider_time_to_live, "little_spider_time_to_live");
	add(&bubble_time_to_live, "bubble_time_to_live");
	add(&bubble_time_to_grow, "bubble_time_to_grow");
	add(&bubble_time_to_hold_mechos, "bubble_time_to_hold_mechos");
	add(&bubble_owner_protection_time, "bubble_owner_protection_time");
	add(&bubble_active_size, "bubble_active_size");
	add(&bubble_restitution_plus_one, "bubble_restitution_plus_one");
	add(&bubble_buoyancy, "bubble_buoyancy");
	add(&bubble_freeHeight, "bubble_freeHeight");
	add(&bubble_cargoHeight, "bubble_cargoHeight");
	add(&bubble_freeGravity, "bubble_freeGravity");
	add(&bubble_cargoGravity, "bubble_cargoGravity");
	add(&bubble_freeWind, "bubble_freeWind");
	add(&bubble_cargoWind, "bubble_cargoWind");
	add(&bubble_field_source_radius_factor, "bubble_field_source_radius_factor");
	add(&bubble_field_z_offset, "bubble_field_z_offset");
	add(&bubble_field_force, "bubble_field_force");
	add(&bubble_field_damping, "bubble_field_damping");
	add(&suicide_time_to_live, "suicide_time_to_live");
	add(&suicide_time_to_live_interface, "suicide_time_to_live_interface");
	add(&suicide_time_to_grow, "suicide_time_to_grow");
	add(&suicide_traction, "suicide_traction");
	add(&suicide_rudder, "suicide_rudder");
	add(&suicide_dragVx, "suicide_dragVx");
	add(&suicide_dragVy, "suicide_dragVy");
	add(&suicide_dragVz, "suicide_dragVz");
	add(&suicide_dragWxy, "suicide_dragWxy");
	add(&suicide_dragWz, "suicide_dragWz");
	add(&suicide_bbox_x, "suicide_bbox_x");
	add(&suicide_bbox_y, "suicide_bbox_y");
	add(&suicide_laps, "suicide_laps");
	add(&suicide_initial_Vy, "suicide_initial_Vy");
	add(&suicide_max_distance_to_attack_mechos, "suicide_max_distance_to_attack_mechos");
	add(&suicide_average_stop_velocity, "suicide_average_stop_velocity");
	add(&suicide_average_stop_delay, "suicide_average_stop_delay");
	add(&suicide_impact_velocity, "suicide_impact_velocity");
	add(&suicide_impact_normal_y, "suicide_impact_normal_y");
	add(&bonus_man_buoyancy, "bonus_man_buoyancy");
	add(&bonus_man_submersion_threshould, "bonus_man_submersion_threshould");
	add(&bonus_man_mechos_hit_velocity, "bonus_man_mechos_hit_velocity");
	add(&bonus_man_switch_time_threshould, "bonus_man_switch_time_threshould");
	add(&bonus_man_shadow_height_threshould, "bonus_man_shadow_height_threshould");
	add(&bonus_man_beeped_distance, "bonus_man_beeped_distance");
	add(&bonus_man_beeped_time, "bonus_man_beeped_time");
	add(&bonus_man_burning_time, "bonus_man_burning_time");
	add(&static_bonus_birth_delay, "static_bonus_birth_delay");
	add(&beeped_bonus_Vxy, "beeped_bonus_Vxy");
	add(&beeped_bonus_Vz, "beeped_bonus_Vz");
	add(&beeped_bonus_W, "beeped_bonus_W");
	add(&meteorite_W, "meteorite_W");
	add(&bonus_meteorite_buoyancy, "bonus_meteorite_buoyancy");
	add(&snow_ball_scale_radius, "snow_ball_scale_radius");
	add(&snow_ball_dragV, "snow_ball_dragV");
	add(&ball_time_to_live, "ball_time_to_live");
	add(&ball_drag_vw, "ball_drag_vw");
	add(&ball_initial_V, "ball_initial_V");
	add(&ball_initial_W, "ball_initial_W");
	add(&ball_buoyancy, "ball_buoyancy");
	add(&ball_traction_factor, "ball_traction_factor");
	add(&ball_steering_factor, "ball_steering_factor");
	add(&ball_max_Vxy, "ball_max_Vxy");
	add(&clown_buoyancy, "clown_buoyancy");
	add(&tomato_mass, "tomato_mass");
	add(&tomato_TOI_scale, "tomato_TOI_scale");
	add(&tomato_radius_scale, "tomato_radius_scale");
	add(&tomato_linear_damping, "tomato_linear_damping");
	add(&tomato_angular_damping, "tomato_angular_damping");
	add(&tomato_return_force, "tomato_return_force");
	add(&tomato_buoyancy, "tomato_buoyancy");
	add(&tomato_swing_lift_force, "tomato_swing_lift_force");
	add(&tomato_swing_torque, "tomato_swing_torque");
	add(&titanium_ball_damage, "titanium_ball_damage");
	add(&titanium_ball_time_to_grow, "titanium_ball_time_to_grow");
	add(&titanium_ball_time_to_live, "titanium_ball_time_to_live");
	add(&titanium_ball_restitution_plus_one, "titanium_ball_restitution_plus_one");
	add(&titanium_ball_mass, "titanium_ball_mass");
	add(&titanium_ball_damping, "titanium_ball_damping");
	add(&titanium_ball_Vxy, "titanium_ball_Vxy");
	add(&titanium_ball_Vz, "titanium_ball_Vz");
	add(&crystal_max_slope, "crystal_max_slope");
	add(&crystal_energy, "crystal_energy");
	add(&crystal_damage_by_mechos, "crystal_damage_by_mechos");
	add_parameter_section(this);
}
};
static AnimalArcansPrm_ParameterSection AnimalArcansPrm_ParameterSectionObject;
#endif  //  _PRM_EDIT_
//////////////////////////////////////////////////////////////////////////////////////////////
//	XScript end: AnimalArcansPrm
//////////////////////////////////////////////////////////////////////////////////////////////
