#include "Sound\snd_ids.h"

// Сила Жизни
/*
#define ARCANE030_body arcane_data $ARCANE030 {      \
	arcane_text	$ARCANE030_text \
	arcane_name	$ARCANE030_name   \
	ANSEED		5		   \
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Щупальце
#define ARCANE036_body arcane_data $ARCANE036 {      \
	arcane_text	$ARCANE036_text \
	arcane_name	$ARCANE036_name   \
	ANSEED		3		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0 \
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Кристаллизация
#define ARCANE009_body arcane_data $ARCANE009 {      \
	arcane_text	$ARCANE009_text \
	arcane_name	$ARCANE009_name   \
	ANSEED		3		   \
	arcane_power	20.0		\
	arcane_delta_power	5000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Титановые шары
#define ARCANE037_body arcane_data $ARCANE037 {      \
	arcane_text	$ARCANE037_text \
	arcane_name	$ARCANE037_name   \
	ANSEED		3		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Гроза
#define ARCANE025_body arcane_data $ARCANE025 {      \
	arcane_text	$ARCANE025_text \
	arcane_name	$ARCANE025_name   \
	ANSEED		4		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Огненный вал
#define ARCANE003_body arcane_data $ARCANE003 {      \
	arcane_text	$ARCANE003_text \
	arcane_name	$ARCANE003_name   \
	ANSEED		5		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Вихрь
/*
#define ARCANE016_body arcane_data $ARCANE016 {      \
	arcane_text	$ARCANE016_text \
	arcane_name	$ARCANE016_name   \
	ANSEED		7		   \
	arcane_power	20.0		\
	arcane_delta_power	20.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Магнитная подушка
/*
#define ARCANE014_body arcane_data $ARCANE014 {      \
	arcane_text	$ARCANE014_text \
	arcane_name	$ARCANE014_name   \
	ANSEED		10		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}
*/

// Муравейник
#define ARCANE018_body arcane_data $ARCANE018 {      \
	arcane_text	$ARCANE018_text \
	arcane_name	$ARCANE018_name   \
	ANSEED		50		   \
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	0		\
}

// Огненные шары
#define ARCANE040_body arcane_data $ARCANE040 { \
	arcane_text	$ARCANE040_text \
	arcane_name	$ARCANE040_name   \
	ANSEED		2		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Статическое электричество
#define ARCANE032_body arcane_data $ARCANE032 { \
	arcane_text	$ARCANE032_text \
	arcane_name	$ARCANE032_name   \
	ANSEED		3		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}


// Нулификация
/*
#define ARCANE022_body arcane_data $ARCANE022 { \
	arcane_text	$ARCANE022_text \
	arcane_name	$ARCANE022_name   \
	ANSEED		2		   \
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Кожа Носорога
/*
#define ARCANE023_body arcane_data $ARCANE023 { \
	arcane_text	$ARCANE023_text \
	arcane_name	$ARCANE023_name   \
	ANSEED		7		   \
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Метеоритный рой
#define ARCANE024_body arcane_data $ARCANE024 { \
	arcane_text	$ARCANE024_text \
	arcane_name	$ARCANE024_name   \
	ANSEED		4		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Электрические Семена
#define ARCANE029_body arcane_data $ARCANE029 { \
	arcane_text	$ARCANE029_text \
	arcane_name	$ARCANE029_name   \
	ANSEED		3		   \
	arcane_power	20.0		\
	arcane_delta_power	5000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Магнитное поле
#define ARCANE015_body arcane_data $ARCANE015 { 	\
	arcane_text	$ARCANE015_text \
	arcane_name	$ARCANE015_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Пауки
#define ARCANE017_body arcane_data $ARCANE017 { 	\
	arcane_text	$ARCANE017_text \
	arcane_name	$ARCANE017_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Мыльные пузыри
#define ARCANE019_body arcane_data $ARCANE019 { 	\
	arcane_text	$ARCANE019_text \
	arcane_name	$ARCANE019_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	10000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}

// Притяжение
/*
#define ARCANE020_body arcane_data $ARCANE020 { 	\
	arcane_text	$ARCANE020_text \
	arcane_name	$ARCANE020_name \
	ANSEED		2		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Гусеницы
#define ARCANE021_body arcane_data $ARCANE021 { 	\
	arcane_text	$ARCANE021_text \
	arcane_name	$ARCANE021_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Полет на ядре
#define ARCANE045_body arcane_data $ARCANE045 { 	\
	arcane_text	$ARCANE045_text \
	arcane_name	$ARCANE045_name \
	ANSEED		5		\
	arcane_power	20.0		\
	arcane_delta_power	3000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Телепорт
#define ARCANE048_body arcane_data $ARCANE048 { 	\
	arcane_text	$ARCANE048_text \
	arcane_name	$ARCANE048_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Cила Дракона
#define ARCANE050_body arcane_data $ARCANE050 { 	\
	arcane_text	$ARCANE050_text \
	arcane_name	$ARCANE050_name \
	ANSEED		2		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}

// Вертолет
#define ARCANE051_body arcane_data $ARCANE051 { 	\
	arcane_text	$ARCANE051_text \
	arcane_name	$ARCANE051_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}


// Жало
/*
#define ARCANE035_body arcane_data $ARCANE035 { 	\
	arcane_text	$ARCANE035_text \
	arcane_name	$ARCANE035_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// X-рентген
#define ARCANE033_body arcane_data $ARCANE033 { 	\
	arcane_text	$ARCANE033_text \
	arcane_name	$ARCANE033_name \
	ANSEED		2		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}


// Кинетический Удар
#define ARCANE034_body arcane_data $ARCANE034 { 	\
	arcane_text	$ARCANE034_text \
	arcane_name	$ARCANE034_name \
	ANSEED		5		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Железный Бок
#define ARCANE038_body arcane_data $ARCANE038 { 	\
	arcane_text	$ARCANE038_text \
	arcane_name	$ARCANE038_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Мастер Вуду
#define ARCANE039_body arcane_data $ARCANE039 { 	\
	arcane_text	$ARCANE039_text \
	arcane_name	$ARCANE039_name \
	ANSEED		9		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}


// Самоубийца
#define ARCANE042_body arcane_data $ARCANE042 { 	\
	arcane_text	$ARCANE042_text \
	arcane_name	$ARCANE042_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Клоун
#define ARCANE041_body arcane_data $ARCANE041 { 	\
	arcane_text	$ARCANE041_text \
	arcane_name	$ARCANE041_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Ярость слизи
#define ARCANE004_body arcane_data $ARCANE004 { 	\
	arcane_text	$ARCANE004_text \
	arcane_name	$ARCANE004_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Бешенная плесень
#define ARCANE005_body arcane_data $ARCANE005 { 	\
	arcane_text	$ARCANE005_text \
	arcane_name	$ARCANE005_name \
	ANSEED		2		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Глаз
#define ARCANE007_body arcane_data $ARCANE007 { 	\
	arcane_text	$ARCANE007_text \
	arcane_name	$ARCANE007_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Алые Следы
#define ARCANE011_body arcane_data $ARCANE011 { 	\
	arcane_text	$ARCANE011_text \
	arcane_name	$ARCANE011_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	7000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Хлопушка
#define ARCANE002_body arcane_data $ARCANE002 { 	\
	arcane_text	$ARCANE002_text \
	arcane_name	$ARCANE002_name \
	ANSEED		1		\
	arcane_power	20.0		\
	arcane_delta_power	1000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Помидор
#define ARCANE012_body arcane_data $ARCANE012 { 	\
	arcane_text	$ARCANE012_text \
	arcane_name	$ARCANE012_name \
	ANSEED		4		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Жабасома
#define ARCANE052_body arcane_data $ARCANE052 { 	\
	arcane_text	$ARCANE052_text \
	arcane_name	$ARCANE052_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}

//Armour(new)
/*
#define ARCANE056_body arcane_data $ARCANE056 { 	\
	arcane_text	$ARCANE056_text \
	arcane_name	$ARCANE056_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

//Insulation(new)
/*
#define ARCANE057_body arcane_data $ARCANE057 { 	\
	arcane_text	$ARCANE057_text \
	arcane_name	$ARCANE057_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

//0-Trasportation(new)
#define ARCANE058_body arcane_data $ARCANE058 { 	\
	arcane_text	$ARCANE058_text \
	arcane_name	$ARCANE058_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	0		\
}

//Butterfly(new)
#define ARCANE059_body arcane_data $ARCANE059 { 	\
	arcane_text	$ARCANE059_text \
	arcane_name	$ARCANE059_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}

//Dirigible(new)
#define ARCANE060_body arcane_data $ARCANE060 { 	\
	arcane_text	$ARCANE060_text \
	arcane_name	$ARCANE060_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0002	\
	arcane_interruption	1		\
}

//Mines(new)
#define ARCANE061_body arcane_data $ARCANE061 { 	\
	arcane_text	$ARCANE061_text \
	arcane_name	$ARCANE061_name \
	ANSEED		3		\
	arcane_power	20.0		\
	arcane_delta_power	10000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}


// Снегопад
#define ARCANE064_body arcane_data $ARCANE064 {      \
	arcane_text	$ARCANE064_text \
	arcane_name	$ARCANE064_name   \
	ANSEED		4		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}

// Ракеты
/*
#define ARCANE065_body arcane_data $ARCANE065 { \
	arcane_text	$ARCANE065_text \
	arcane_name	$ARCANE065_name   \
	ANSEED		2		   \
	arcane_power	20.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	20.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Искрение
#define ARCANE066_body arcane_data $ARCANE066 { \
	arcane_text	$ARCANE066_text \
	arcane_name	$ARCANE066_name   \
	ANSEED		2		   \
	arcane_power	20.0		\
	arcane_delta_power	20000.0	\
	arcane_activate_power	4.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}

// Energy
bonus_arcane $ARCANE053 {
	time		60
//	arcane_name	$ARCANE053_name
	type		2
}


// Jump
bonus_arcane $ARCANE054 {
	time		60
//	arcane_name	$ARCANE054_name
	type		-1
}

// Nitro
bonus_arcane $ARCANE055 {
	time		60
//	arcane_name	$ARCANE055_name
	type		1
}

// Spell
bonus_arcane $ARCANE062 {
	time		60
//	arcane_name	$ARCANE062_name
	type		3
}

// Star
bonus_arcane $ARCANE063 {
	time		60
//	arcane_name	$ARCANE063_name
	type		4
}

//SpeedIncrement
bonus_arcane $ARCANE067 {
	time		60
//	arcane_name	$ARCANE067_name
	type		-1
}

//FireProtection
bonus_arcane $ARCANE068 {
	time		60
//	arcane_name	$ARCANE068_name
	type		-1
}

//FireProtection
bonus_arcane $ARCANE069 {
	time		60
//	arcane_name	$ARCANE069_name
	type		-1
}

//FireProtection
bonus_arcane $ARCANE070 {
	time		60
//	arcane_name	$ARCANE070_name
	type		-1
}

//BioPower
bonus_arcane $ARCANE071 {
	time		60
//	arcane_name	$ARCANE071_name
	type		-1
}

//-----------------------RESERVE-------------------

// Землетрясение
/*
#define ARCANE026_body arcane_data $ARCANE026 {      \
	arcane_name	$ARCANE026_name   \
	ANSEED		10		   \
	arcane_power	10.0		\
	arcane_delta_power	10.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Темнота
/*
#define ARCANE027_body arcane_data $ARCANE027 { \
	arcane_name	$ARCANE027_name   \
	ANSEED		3		   \
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Зона
/*
#define ARCANE028_body arcane_data $ARCANE028 { \
	arcane_name	$ARCANE028_name   \
	ANSEED		1		   \
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Резиновый лужек
/*
#define ARCANE013_body arcane_data $ARCANE013 { 	\
	arcane_name	$ARCANE013_name \
	ANSEED		10		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Buble Gum
/*
#define ARCANE008_body arcane_data $ARCANE008 { 	\
	arcane_name	$ARCANE008_name \
	ANSEED		1		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Парализатор
/*
#define ARCANE031_body arcane_data $ARCANE031 { \
	arcane_name	$ARCANE031_name   \
	ANSEED		2		   \
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Ветер Астрала
/*
#define ARCANE044_body arcane_data $ARCANE044 { 	\
	arcane_name	$ARCANE044_name \
	ANSEED		1		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/


// Цаплеморф
/*
#define ARCANE047_body arcane_data $ARCANE047 { 	\
	arcane_name	$ARCANE047_name \
	ANSEED		4		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	1		\
}
*/

// Упругий Бок
/*
#define ARCANE043_body arcane_data $ARCANE043 { 	\
	arcane_name	$ARCANE043_name \
	ANSEED		1		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Песчаная Жатва
/*
#define ARCANE010_body arcane_data $ARCANE010 { 	\
	arcane_name	$ARCANE010_name \
	ANSEED		1		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Гнус
/*
#define ARCANE006_body arcane_data $ARCANE006 { 	\
	arcane_name	$ARCANE006_name \
	ANSEED		4		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Прыжок
/*
#define ARCANE046_body arcane_data $ARCANE046 { 	\
	arcane_name	$ARCANE046_name \
	ANSEED		1		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/

// Парение
/*
#define ARCANE049_body arcane_data $ARCANE049 { 	\
	arcane_name	$ARCANE049_name \
	ANSEED		3		\
	arcane_power	10.0		\
	arcane_delta_power	1.0	\
	arcane_activate_power	10.0	\
	arcane_charge_power	0.0003	\
	arcane_interruption	0		\
}
*/