
#define M3D_3DS_PATH		1
#define M3D_BMP_PATH		2
#define M3D_OBJECT		3
#define M3D_Type		4	
#define M3D_SCALE		5
#define M3D_SCALE_X		6  
#define M3D_SCALE_Y		7 
#define M3D_SCALE_Z		8 
#define M3D_3DS_FILE		9 
#define M3D_SIZE		11
#define M3D_SIZE_X		12
#define M3D_SIZE_Y		13
#define M3D_SIZE_Z		14
#define M3D_SOUND_ID		15

#define M3D_MORPH_FILE	16
#define M3D_MORPH_TIME	17
#define M3D_ANIMATION_PHASE	18	
#define M3D_ANIMATION_PERIOD	19
#define M3D_SET_PIVOT	20
#define M3D_ATTRIBUTE	21

// Global parameter
#define M3D_DEFAULT_ATTRIBUTE	200

#define M3D_ARCANE					100
#define M3D_ARCANE_NAME				101
#define M3D_ARCANE_ANSEED			102
#define M3D_ARCANE_POWER			103
#define M3D_ARCANE_DELTA_POWER		104
#define M3D_ARCANE_ACTIVATE_POWER	105
#define M3D_ARCANE_CHARGE_POWER		106
#define M3D_ARCANE_INTERRUPTION		107
#define M3D_BONUS_TIMER				108
#define M3D_BONUS					109
#define M3D_ARCANE_TEXT			110
