#define WORLDSCRIPT_DEFOBJECT3D_PATH			1
#define WORLDSCRIPT_DEFTEXTURE_PATH				2
#define WORLDSCRIPT_NAME_WSC					3
#define WORLDSCRIPT_SOUNDSCRIPT					4
#define WORLDSCRIPT_MUSICTRACK					5

#define WORLDSCRIPT_ANIMSCRIPT					10
#define WORLDSCRIPT_OBJECT3D_PATH				11
#define WORLDSCRIPT_VISIBLEOBJECT				12
#define WORLDSCRIPT_INVISIBLEOBJECT				13
#define WORLDSCRIPT_VISIBLEALLOBJECT			14

#define WORLDSCRIPT_TEXT						20
#define WORLDSCRIPT_ANIMATION					21
#define WORLDSCRIPT_POSXY						22
#define WORLDSCRIPT_FONTSIZE					23
#define WORLDSCRIPT_NUMBERFONT					24
#define WORLDSCRIPT_COLORFONT					25
#define WORLDSCRIPT_CENTERED					26

#define WORLDSCRIPT_SOUND						40
#define	WORLDSCRIPT_PARENT						41

#define WORLDSCRIPT_LIGHTING					50
#define WORLDSCRIPT_STARTCOLOR					51
#define WORLDSCRIPT_FINISHCOLOR					52

#define WORLDSCRIPT_SKY							60
