#define WORLD_DEFAULT_OBJECT3D_PATH				1
#define WORLD_DEFAULT_TEXTURE_PATH				2
#define WORLD_DEFAULT_WATER_PATH				3
#define WORLD_DEFAULT_ATTRIBUTE					4
#define WORLD_DEFAULT_AIR_HEIGHT				5
#define WORLD_DEFAULT_CLOUD_HEIGHT				6
#define WORLD_RADIUS_SHARE						7
#define WORLD_DEFAULT_TEXTURE_SUN				8
#define WORLD_DEFAULT_TEXTURE_MOON				9
#define WORLD_DEFAULT_FILE_TILEMAP				10
#define WORLD_DEFAULT_FILE_OBJECTMAP			11
#define WORLD_DEFAULT_FILE_OMNIMAP				12

#define WORLD_STRUCT							20
#define WORLD_OBJECT3D_PATH						21
#define WORLD_TEXTURE_PATH						22
#define WORLD_FILE_TILEMAP						23
#define WORLD_FILE_OBJECTMAP					24
#define WORLD_FILE_OMNIMAP						25
#define WORLD_ATTRIBUTE							26

#define WORLD_WATER_TILESIZE					40
#define WORLD_WATER_TEXTURE						41
#define WORLD_WATER_ENVMAP						42
#define WORLD_WATER_TEXTURE_SCALE				43
#define WORLD_WATER_TEXTURE_VELOCITYX			44
#define WORLD_WATER_TEXTURE_VELOCITYY			45

#define WORLD_AIR_TEXTURE						60
#define WORLD_AIR_TILESIZE						61
#define WORLD_AIR_TEXTURE_SCALE					62
#define WORLD_AIR_TEXTURE_VELOCITYX				63
#define WORLD_AIR_TEXTURE_VELOCITYY				64

#define WORLD_CLOUD_TEXTURE						80
#define WORLD_CLOUD_OPACITY						81
#define WORLD_CLOUD_TILESIZE					82
#define WORLD_CLOUD_TEXTURE_SCALE				83
#define WORLD_CLOUD_TEXTURE_VELOCITYX			84
#define WORLD_CLOUD_TEXTURE_VELOCITYY			85

#define WORLD_COLOR_AMBIENT_AIR					100
#define WORLD_REFLECTION_SURFACE				101
#define WORLD_COLOR_AMBIENT_OBJECT				102