
#define FXLAB_SCRIPT_SECTION_KEY		0
#define FXLAB_SCRIPT_SECTION_SPRITE		1
#define FXLAB_SCRIPT_SECTION_MAX		2

//---------------------------------------------

//Key Definition
#define FXLAB_SCRIPT_KEY_ID				0
#define FXLAB_SCRIPT_KEY_DEFINITION		1
#define FXLAB_SCRIPT_KEY_TIME			2
#define FXLAB_SCRIPT_KEY_DATA			3
#define FXLAB_SCRIPT_KEY_NAME			4
#define FXLAB_SCRIPT_KEY_ATTRIBUTE		5
#define FXLAB_SCRIPT_KEY_MODE			6

//Key Status
#define FXLAB_KEY_ATTRIBUTE_NONE		0
#define FXLAB_KEY_ATTRIBUTE_REPEAT		1
#define FXLAB_KEY_ATTRIBUTE_FREEZE		2
#define FXLAB_KEY_ATTRIBUTE_STORAGE		4

//KeyMode
#define FXLAB_KEY_MODE_IMPULSE			0
#define	FXLAB_KEY_MODE_LINEAR			1

//-----------------------------------------------

//Sprite Definition

#define FXLAB_SCRIPT_SPRITE_ID			0
#define FXLAB_SCRIPT_SPRITE_PHASE_NUM	1
#define FXLAB_SCRIPT_SPRITE_KEY_ID		2
#define FXLAB_SCRIPT_SPRITE_TEXTURE_ID	3

//-----------------------------------------------

//ClientSet Definition
#define FXLAB_CLIENT_SET_MODE_NONE			0
#define FXLAB_CLIENT_SET_MODE_WAIT			1
#define FXLAB_CLIENT_SET_MODE_DESTROY		2

//DamageSphere Definition
#define FXLAB_DAMAGE_SPHERE_TYPE_GENERIC		0
#define FXLAB_DAMAGE_SPHERE_TYPE_FIRE			1
#define FXLAB_DAMAGE_SPHERE_TYPE_LIGHTNING		2
#define FXLAB_DAMAGE_SPHERE_TYPE_CHARGE_ENERGY	3
#define FXLAB_DAMAGE_SPHERE_TYPE_CHARGE_MANA	4
#define FXLAB_DAMAGE_SPHERE_TYPE_KINETIC		5

//Domain ID
#define FXLAB_SWARM_DOMAIN_POINT			0
#define FXLAB_SWARM_DOMAIN_LINE				1
#define FXLAB_SWARM_DOMAIN_SPHERE			2
#define FXLAB_SWARM_DOMAIN_CYLINDER			3
#define FXLAB_SWARM_DOMAIN_CONE				4
#define FXLAB_SWARM_DOMAIN_CIRCLE			5
#define FXLAB_SWARM_DOMAIN_POLAR_SPHERE		6
#define FXLAB_SWARM_DOMAIN_ISO_SPHERE		7
#define FXLAB_SWARM_DOMAIN_BOX				8

//--------------------------------------------------------

//ClientIDs
#define FXLAB_CLIENT_PROCESS_TWISTER				0
#define FXLAB_CLIENT_PROCESS_RUBBER_SNAKE			1
#define FXLAB_CLIENT_PROCESS_EXPLODE				2
#define FXLAB_CLIENT_PROCESS_TAIL					3
#define FXLAB_CLIENT_PROCESS_DUST					4
#define FXLAB_CLIENT_PROCESS_FEAR_FIRE				5
#define FXLAB_CLIENT_PROCESS_SPARK_GENERATOR		6
#define FXLAB_CLIENT_PROCESS_FEAR_STREAM			7
#define FXLAB_CLIENT_PROCESS_TAIL_WATER_CLIP		8
#define FXLAB_CLIENT_PROCESS_DUST_WATER_CLIP		9
#define FXLAB_CLIENT_PROCESS_SPARK_WATER_CLIP		10
#define FXLAB_CLIENT_PROCESS_COLOR_MODEL			11
#define FXLAB_CLIENT_PROCESS_CONTROL_MODEL			12
#define FXLAB_CLIENT_PROCESS_CHECK_POINT			13
#define FXLAB_CLIENT_PROCESS_POLAR_MODEL			14
#define FXLAB_CLIENT_PROCESS_CONTROL_OMNI			15
#define FXLAB_CLIENT_PROCESS_OBJECT_SET				16
#define FXLAB_CLIENT_PROCESS_BODY_LINK				17
#define FXLAB_CLIENT_PROCESS_WAVE_GROUND			18
#define FXLAB_CLINET_PROCESS_BONUS_MODEL			19
#define FXLAB_CLINET_PROCESS_BONUS_PART				20
#define FXLAB_CLIENT_PROCESS_OBJECT_LAUNCHER		21
#define FXLAB_CLIENT_PROCESS_OBJECT_SWITCHER		22
#define FXLAB_CLIENT_PROCESS_REMOTE_SWITCHER		23

#define FXLAB_CLIENT_PROCESS_MECHOS_LINK				24
#define FXLAB_CLIENT_PROCESS_FRONT_LINK					25
#define FXLAB_CLIENT_PROCESS_BACK_LINK					26
#define FXLAB_CLIENT_PROCESS_LEFTFORWARD_WHEEL_LINK		27
#define FXLAB_CLIENT_PROCESS_RIGHTFORWARD_WHEEL_LINK	28
#define FXLAB_CLIENT_PROCESS_LEFTBACK_WHEEL_LINK		29
#define FXLAB_CLIENT_PROCESS_RIGHTBACK_WHEEL_LINK		30

#define FXLAB_CLIENT_PROCESS_WILD_CLAW					31

#define FXLAB_CLIENT_PROCESS_STREAM_CLUSTER				32

#define FXLAB_CLIENT_PROCESS_SPARK_WIND					33
#define FXLAB_CLIENT_PROCESS_SPARK_WIND_WATER_CLIP		34

#define FXLAB_CLIENT_PROCESS_LIGHTNING_SPHERE			35
#define FXLAB_CLIENT_PROCESS_LIGHTNING_LINE				36
#define FXLAB_CLIENT_PROCESS_LIGHTNING_RADIUS			37

#define	FXLAB_CLIENT_PROCESS_BOW_MACHINE				38
#define FXLAB_CLIENT_PROCESS_BOW_MACHINE_FRONT_LINK		39
#define FXLAB_CLIENT_PROCESS_WILD_CLAW_FRONT_LINK		40

#define FXLAB_CLIENT_PROCESS_LEFT_BALL_WIND_LINK		41
#define FXLAB_CLIENT_PROCESS_RIGHT_BALL_WIND_LINK		42

#define FXLAB_CLIENT_PROCESS_SUICIDE_LINK				43

#define FXLAB_CLIENT_PROCESS_SLIME_MODEL				44

#define FXLAB_CLIENT_PROCESS_ANIMATION_MODEL			45

#define FXLAB_CLIENT_PROCESS_LASH_MODEL					46
#define FXLAB_CLIENT_PROCESS_VOODOO_HEAD_MODEL			47
#define FXLAB_CLIENT_PROCESS_VOODOO_MASTER				48

#define FXLAB_CLIENT_PROCESS_TERRAIN_DEFORMATOR			49

#define FXLAB_CLIENT_PROCESS_SPARK_GENERATOR_EXTERNAL	51

#define FXLAB_CLIENT_PROCESS_PRESSURE_MODEL				52
#define FXLAB_CLIENT_PROCESS_REVOLT_SPACE_LINK			53

#define FXLAB_CLIENT_PROCESS_MASS_SHIFTER_MODEL			54
#define FXLAB_CLIENT_PROCESS_MASS_SHIFTER				55

#define FXLAB_CLIENT_PROCESS_ACTION_JUMP_LEFT			56
#define FXLAB_CLIENT_PROCESS_ACTION_JUMP_RIGHT			57
#define FXLAB_CLIENT_PROCESS_ACTION_NITRO_LEFT			58
#define FXLAB_CLIENT_PROCESS_ACTION_NITRO_RIGHT			59

#define FXLAB_CLIENT_PROCESS_MECHOS_FIRE				60
#define FXLAB_CLIENT_PROCESS_MECHOS_CONTROLLER			61
#define FXLAB_CLIENT_PROCESS_COLOR_CONTROLLER			62

#define FXLAB_CLIENT_PROCESS_SOUND_IMPULSE				63
#define FXLAB_CLIENT_PROCESS_SOUND_SPACE_IMPULSE		64
#define FXLAB_CLIENT_PROCESS_SOUND_LONG					65
#define FXLAB_CLIENT_PROCESS_SOUND_SPACE_LONG			66

#define FXLAB_CLIENT_PROCESS_BOLIDE_LINK				67
#define FXLAB_CLIENT_PROCESS_HEAD_DUST_LAUNCHER			68
#define FXLAB_CLIENT_PROCESS_FIRE_BALL_LINK				69
#define FXLAB_CLIENT_PROCESS_LIGHTNING_BOLT_LINK		70
#define FXLAB_CLIENT_PROCESS_LIGHTNING_SEED				71

#define FXLAB_CLIENT_PROCESS_SHAFT_MECHINE_FRONT_LINK	72
#define FXLAB_CLIENT_PROCESS_VOLCANIC_STONE_LINK		73
#define FXLAB_CLIENT_PROCESS_BOMB_EXPLODE_LINK			74

#define FXLAB_CLIENT_PROCESS_DRAGON_FIRE_SWITCHER		75
#define FXLAB_CLIENT_PROCESS_DRAGON_HEAD_FIRE_SWITCHER	76

#define FXLAB_CLIENT_PROCESS_REVOLT_MODEL				77
#define FXLAB_CLIENT_PROCESS_GROUND_MODEL				78
#define FXLAB_CLIENT_PROCESS_MORTAR_BODY_LINK			79
#define FXLAB_CLIENT_PROCESS_PETARD_MODEL				80

#define FXLAB_CLIENT_PROCESS_SPARK_LINE					81

#define FXLAB_CLIENT_PROCESS_PART_CONTROLLER			82

#define FXLAB_CLIENT_PROCESS_TELEPORT_COLOR_CONTROLLER	83
#define FXLAB_CLIENT_PROCESS_TELEPORT_OMNI_CONTROLLER	84

#define FXLAB_CLIENT_PROCESS_SNOW_LAYER					85

#define FXLAB_CLIENT_PROCESS_BONUS_BODY_LINK			86

#define FXLAB_CLIENT_PROCESS_SNOW_FALL_LINK				87
#define FXLAB_CLIENT_PROCESS_MECHOS_BURN_LINK			88
#define FXLAB_CLIENT_PROCESS_BOMB_SPLINTER_LINK			89

#define FXLAB_CLIENT_PROCESS_JUMP_ACTION_MODEL			90
#define FXLAB_CLIENT_PROCESS_JUMP_ACTION_LINK			91
#define FXLAB_CLIENT_PROCESS_NITRO_ACTION_LINK			92

#define	FXLAB_CLIENT_PROCESS_WATER_WAVE_MODEL			93

#define FXLAB_CLIENT_PROCESS_MASS_SHIFTER_NITRO			94

#define FXLAB_CLIENT_PROCESS_BULLET_SNOW_MODEL			95
#define FXLAB_CLIENT_PROCESS_BULLET_FIRE_MODEL			96

#define FXLAB_CLIENT_PROCESS_VOODOO_MASTER_LINK			97

#define FXLAB_CLIENT_PROCESS_WORLD_IRRADIATE			98

#define FXLAB_CLIENT_PROCESS_MASS_SHIFTER_CHARACTER		99

#define FXLAB_CLIENT_PROCESS_SPLINE_WAY					100

#define FXLAB_CLIENT_PROCESS_SET_FACE_FIRE				101

#define FXLAB_CLIENT_PROCESS_MOVIE_BOW_REPEATER			102

#define FXLAB_CLIENT_PROCESS_MOVIE_WAVE_REPEATER		103

#define FXLAB_CLIENT_PROCESS_WIND_SOUND					104

#define FXLAB_CLIENT_PROCESS_MOVIE_QUAD_LIGHT			105

#define FXLAB_CLIENT_PROCESS_MOVIE_CLOUDS				106

#define FXLAB_CLIENT_PROCESS_MOVIE_SHIFTING				107
#define FXLAB_CLIENT_PROCESS_MASS_SHIFTER_MOVIE			108
#define FXLAB_CLIENT_PROCESS_MOVIE_TELEPORT				109

#define FXLAB_CLIENT_PROCESS_FIRE_TREE_MOVIE			110

#define FXLAB_CLIENT_PROCESS_MOVIE_SPOT					111

#define FXLAB_CLIENT_PROCESS_MOVIE_BOSS_CHANGE			112

#define FXLAB_CLIENT_PROCESS_CHARACTER_WAVE_GENERATOR	113

#define FXLAB_CLIENT_PROCESS_STREAM_FOUNTAIN			114

#define FXLAB_CLIENT_PROCESS_BOSS_STEAM_GENERATOR		115
#define FXLAB_CLIENT_PROCESS_BOSS_SMOKE_GENERATOR		116

#define FXLAB_CLIENT_PROCESS_BOSS_WATERFALL_GENERATOR	117
		
#define FXLAB_CLIENT_PROCESS_BOSS_WORLD_BURST			118
#define FXLAB_CLIENT_PROCESS_BOSS_WORLD_EXPLOSION		119

#define FXLAB_CLIENT_PROCESS_MOVIE_DRAGON_FIRE			120

#define FXLAB_CLIENT_PROCESS_MOVIE_ROCKET_FIRE			121

//----------------------------------------------------------

//ServerIDs
#define FXLAB_SERVER_PROCESS_DAMAGE_SENSOR			0
#define FXLAB_SERVER_PROCESS_DAMAGE_LINE			1
#define FXLAB_SERVER_PROCESS_BODY_LINK				2
#define FXLAB_SERVER_PROCESS_BONUS					3
#define FXLAB_SERVER_PROCESS_BONUS_SINGLE			4
#define FXLAB_SERVER_PROCESS_BONUS_MARKET			5
#define FXLAB_SERVER_PROCESS_DRAGON_FIRE			6
#define FXLAB_SERVER_PROCESS_SUCK_DAMAGE			7
#define FXLAB_SERVER_PROCESS_WILD_CLAW				8
#define FXLAB_SERVER_PROCESS_PLASMA_CLAW			9
#define FXLAB_SERVER_PROCESS_BOMB_EXPLOSION			10
#define FXLAB_SERVER_PROCESS_VOLCANIC_LAUNCHER		11
#define FXLAB_SERVER_PROCESS_DRAGON_ROSE			12

#define FXLAB_SERVER_PROCESS_VORTEX_FIELD			13
#define FXLAB_SERVER_PROCESS_MAGNETIC_FIELD			14
#define FXLAB_SERVER_PROCESS_FLUX_FIELD				15
#define FXLAB_SERVER_PROCESS_WIND_FIELD				16
		
#define FXLAB_SERVER_PROCESS_WILD_THICKET_CIRCLE	17
#define FXLAB_SERVER_PROCESS_RAGE_SLIME_CIRCLE		18
#define FXLAB_SERVER_PROCESS_RED_TRACK_CIRCLE		19
#define FXLAB_SERVER_PROCESS_GREEN_SLIME_CIRCLE		20
#define FXLAB_SERVER_PROCESS_YELLOW_SLIME_CIRCLE	21
#define FXLAB_SERVER_PROCESS_BLUE_SLIME_CIRCLE		22

#define FXLAB_SERVER_PROCESS_BOW_MACHINE_DAMAGE		23

#define FXLAB_SERVER_PROCESS_DAMAGE_CIRCLE			24
#define FXLAB_SERVER_PROCESS_LIGHTNING_SEED_DAMAGE	25
#define FXLAB_SERVER_PROCESS_MASS_SHIFTER			27
#define FXLAB_SERVER_PROCESS_MECHOS_FIRE			28
#define FXLAB_SERVER_PROCESS_CHARGE_ENERGY			29
#define FXLAB_SERVER_PROCESS_CHARGE_MANA			30
#define FXLAB_SERVER_PROCESS_DRAGON_HEAD_FIRE		31
#define FXLAB_SERVER_PROCESS_TRAP_SPHERE			32
#define FXLAB_SERVER_PROCESS_TRAP_PROCESS			33

#define FXLAB_SERVER_PROCESS_SKIN_PROTECTION		34
#define FXLAB_SERVER_PROCESS_ISOLATION_PROTECTION	35
#define FXLAB_SERVER_PROCESS_ARMOR_PROTECTION		36

#define	FXLAB_SERVER_PROCESS_STATIC_TELEPORT		37

#define FXLAB_SERVER_PROCESS_BIO_PROTECTION			38

#define FXLAB_SERVER_PROCESS_SERVER_VOODOO_HEAD		39

#define FXLAB_SERVER_PROCESS_MECHOS_FROZEN			40

#define FXLAB_SERVER_PROCESS_PERESTROYKA_CLAW		41


#define FXLAB_SERVER_PROCESS_ARCANE					300

#define FXLAB_SERVER_PROCESS_ARCANE_DRAGON_WIND		301
#define FXLAB_SERVER_PROCESS_ARCANE_DIRIGIBLE_WIND	302
#define FXLAB_SERVER_PROCESS_ARCANE_BUTTERFLY_WIND	303
#define FXLAB_SERVER_PROCESS_ARCANE_FROG_WIND		304
#define FXLAB_SERVER_PROCESS_ARCANE_HELICOPTER		305
#define FXLAB_SERVER_PROCESS_ARCANE_PLASMA_CLAW		306
#define FXLAB_SERVER_PROCESS_ARCANE_BOW_MACHINE		307
#define FXLAB_SERVER_PROCESS_ARCANE_SHAFT_MACHINE	308
#define FXLAB_SERVER_PROCESS_ARCANE_FORMICARY_WIND	309
#define FXLAB_SERVER_PROCESS_ARCANE_IRON_SIDE		310
#define FXLAB_SERVER_PROCESS_ARCANE_BALL_WIND		311
#define FXLAB_SERVER_PROCESS_ARCANE_SUICIDE_WARRIOR	312
#define FXLAB_SERVER_PROCESS_ARCANE_CLOWN_WARRIOR	313
#define FXLAB_SERVER_PROCESS_ARCANE_EYE_WARRIOR		314
#define FXLAB_SERVER_PROCESS_ARCANE_TOMATO_WARRIOR	315
#define FXLAB_SERVER_PROCESS_ARCANE_FIREBALL		316
#define FXLAB_SERVER_PROCESS_ARCANE_LIGHTNING_BOLT	317
#define FXLAB_SERVER_PROCESS_ARCANE_JUMP_BALL		318
#define FXLAB_SERVER_PROCESS_ARCANE_SPIDER_SPAWN		319
#define FXLAB_SERVER_PROCESS_ARCANE_CATERPILLAR_SPAWN	320
#define FXLAB_SERVER_PROCESS_ARCANE_FIRE_STONE			321
#define FXLAB_SERVER_PROCESS_ARCANE_SNOW_FALL			322
#define FXLAB_SERVER_PROCESS_ARCANE_ELECTRIC_STORM		323
#define FXLAB_SERVER_PROCESS_ARCANE_FIRE_GARDEN			324
#define FXLAB_SERVER_PROCESS_ARCANE_RAGE_SLIME			325
#define FXLAB_SERVER_PROCESS_ARCANE_FURY_FUNGUS			326
#define FXLAB_SERVER_PROCESS_ARCANE_VOODOO_MASTER		227
#define FXLAB_SERVER_PROCESS_ARCANE_KINETIC_HIT			228
#define FXLAB_SERVER_PROCESS_ARCANE_LIGHNING_SEED		229
#define FXLAB_SERVER_PROCESS_ARCANE_CRYSTAL_SPIKE		230
#define FXLAB_SERVER_PROCESS_ARCANE_REVOLT_SPACE		231
#define FXLAB_SERVER_PROCESS_ARCANE_MASS_SHIFTER		232
#define FXLAB_SERVER_PROCESS_ARCANE_BUBBLE_RUSH			233
#define FXLAB_SERVER_PROCESS_ARCANE_SHIFT_TRAP			234
#define FXLAB_SERVER_PROCESS_ARCANE_MORTAR_MINE			235
#define FXLAB_SERVER_PROCESS_ARCANE_PETARD				236
#define FXLAB_SERVER_PROCESS_ARCANE_SCARLET_TRACK		237
#define FXLAB_SERVER_PROCESS_ARCANE_RED_TRACK			238

//---------------------------------------------
//Sprite Definition

#define FXLAB_ID_SPRITE_TAKE_BONUS_CHARGE	0
#define FXLAB_ID_SPRITE_TAKE_BONUS_JUMP		1
#define FXLAB_ID_SPRITE_TAKE_BONUS_NITRO	2
#define FXLAB_ID_SPRITE_TAKE_BONUS_MANA		3
#define FXLAB_ID_SPRITE_TAKE_BONUS_STARS	4
#define FXLAB_ID_SPRITE_FISHWATER			5
#define FXLAB_ID_SPRITE_WATERPUMP			6
#define FXLAB_ID_SPRITE_DRAGON_FIRE			7
#define FXLAB_ID_SPRITE_WILD_CLAW			8
#define FXLAB_ID_SPRITE_CANNON_DUST			9
#define FXLAB_ID_SPRITE_EXPLOSION_FIRE		10
#define FXLAB_ID_SPRITE_VOLCANIC_FIRE		11
#define FXLAB_ID_SPRITE_VOLCANIC_DUST		12
#define FXLAB_ID_SPRITE_VOLCANIC_STONE_FIRE	13
#define FXLAB_ID_SPRITE_ROSE_FIRE			14
#define FXLAB_ID_SPRITE_HEAD_BREATH			15
#define FXLAB_ID_SPRITE_LAVA_WIND			16
#define FXLAB_ID_SPRITE_WATER_BUBBLE_FLUX		17
#define FXLAB_ID_SPRITE_FOREST_BUBBLE_FLUX		18
#define FXLAB_ID_SPRITE_STONE_BUBBLE_FLUX		19
#define FXLAB_ID_SPRITE_ALTAR_FIRE				20
#define FXLAB_ID_SPRITE_ALTAR_DUST				21
#define FXLAB_ID_SPRITE_HEAD_STREAM				22
#define FXLAB_ID_SPRITE_BALLWIND_PASSIVE		23
#define FXLAB_ID_SPRITE_BALLWIND_ACTIVE			24
#define FXLAB_ID_SPRITE_SUICIDE_FIRE			25
#define FXLAB_ID_SPRITE_CLOWN_RED				26
#define FXLAB_ID_SPRITE_CLOWN_ORANGE			27
#define FXLAB_ID_SPRITE_CLOWN_YELLOW			28
#define FXLAB_ID_SPRITE_CLOWN_GREEN				29
#define FXLAB_ID_SPRITE_CLOWN_LIGHT_BLUE		30
#define FXLAB_ID_SPRITE_CLOWN_BLUE				31
#define FXLAB_ID_SPRITE_CLOWN_MAGENTA			32
#define FXLAB_ID_SPRITE_TOMATO					33
#define FXLAB_ID_SPRITE_FIREBALL				34
#define FXLAB_ID_SPRITE_LIGHTNING_BOLT_SPARK	35
#define FXLAB_ID_SPRITE_FIRE_CLOUDS				36
#define FXLAB_ID_SPRITE_SNOW_CLOUDS				37
#define FXLAB_ID_SPRITE_STORM_CLOUDS			38
#define FXLAB_ID_SPRITE_FURY_FUNGUS_FOG			39
#define FXLAB_ID_SPRITE_VOODOO_HEAD				40
#define FXLAB_ID_SPRITE_LIGHTNING_SPARK			41
#define FXLAB_ID_SPRITE_SPIKE_BURST				42

#define FXLAB_ID_SPRITE_CHARGE_ENERGY			43
#define FXLAB_ID_SPRITE_CHARGE_MANA				44
#define FXLAB_ID_SPRITE_JUMP_ACTION				45
#define FXLAB_ID_SPRITE_NITRO_ACTION			46
#define FXLAB_ID_SPRITE_PLACE_ENERGY_FOG		47
#define FXLAB_ID_SPRITE_PLACE_ENERGY_STAR		48
#define FXLAB_ID_SPRITE_PLACE_MANA_STAR			49

#define FXLAB_ID_SPRITE_MECHOS_FIRE				50
#define FXLAB_ID_SPRITE_MECHOS_BUBBLE			51
#define FXLAB_ID_SPRITE_MECHOS_BURN				52

#define FXLAB_ID_SPRITE_TELEPORT_BURN			53

#define FXLAB_ID_SPRITE_MECHOS_DUST000			54
#define FXLAB_ID_SPRITE_DAMAGE_WARNING			55

#define FXLAB_ID_SPRITE_BUBBLE_RUSH				56

#define FXLAB_ID_SPRITE_MINE_DUST				57

#define FXLAB_ID_SPRITE_TELEPORT_BURN_LAST		58
#define FXLAB_ID_SPRITE_LAVA_ALTAR_FIRE			59

#define FXLAB_ID_SPRITE_SCARLET_TRACK_LINE		60

#define FXLAB_ID_SPRITE_STONE_DUST				61

#define FXLAB_ID_SPRITE_SNOW_LAYER				62

//TownDust
#define FXLAB_ID_SPRITE_MECHOS_DUST302			63
#define FXLAB_ID_SPRITE_MECHOS_DUST303			64
#define FXLAB_ID_SPRITE_MECHOS_DUST305			65

//LavaDust
#define FXLAB_ID_SPRITE_MECHOS_DUST400			66
#define FXLAB_ID_SPRITE_MECHOS_DUST402			67
#define FXLAB_ID_SPRITE_MECHOS_DUST412			68

//WaterDust
#define FXLAB_ID_SPRITE_MECHOS_DUST100			69
#define FXLAB_ID_SPRITE_MECHOS_DUST102			70
#define FXLAB_ID_SPRITE_MECHOS_DUST142			71

//ForestDust
//0
#define FXLAB_ID_SPRITE_MECHOS_DUST200			72
#define FXLAB_ID_SPRITE_MECHOS_DUST202			73
#define FXLAB_ID_SPRITE_MECHOS_DUST207			74

//1
#define FXLAB_ID_SPRITE_MECHOS_DUST210			75
#define FXLAB_ID_SPRITE_MECHOS_DUST212			76

//2
#define FXLAB_ID_SPRITE_MECHOS_DUST220			77
#define FXLAB_ID_SPRITE_MECHOS_DUST222			78
#define FXLAB_ID_SPRITE_MECHOS_DUST227			79

//3
#define FXLAB_ID_SPRITE_MECHOS_DUST230			80
#define FXLAB_ID_SPRITE_MECHOS_DUST232			81
#define FXLAB_ID_SPRITE_MECHOS_DUST237			82

//4
#define FXLAB_ID_SPRITE_MECHOS_DUST240			83
#define FXLAB_ID_SPRITE_MECHOS_DUST242			84

//WhiteStone
#define FXLAB_ID_SPRITE_WHITE_STONE_DUST		85

//TakeBonusProtection
#define FXLAB_ID_SPRITE_TAKE_BONUS_PROTECTION_FIRE			86
#define FXLAB_ID_SPRITE_TAKE_BONUS_PROTECTION_ELECTRIC		87
#define FXLAB_ID_SPRITE_TAKE_BONUS_PROTECTION_ARMOR			88
#define FXLAB_ID_SPRITE_TAKE_BONUS_PROTECTION_BIO			89

//SnowFall
#define FXLAB_ID_SPRITE_SNOW_FALL_EXPLOSION					90
#define FXLAB_ID_SPRITE_SNOW_FALL							91
#define FXLAB_ID_SPRITE_SNOW_BULLET							92

#define FXLAB_ID_SPRITE_FIRE_BULLET							93

#define	FXLAB_ID_SPRITE_BONUS_FIRE							94

#define FXLAB_ID_SPRITE_DRAGON_ROSE						95

#define FXLAB_ID_SPRITE_SPLINE_WAY						96

#define FXLAB_ID_SPRITE_MOVIE_HEAD_FIRE					97
#define FXLAB_ID_SPRITE_MOVIE_SPRAY						98

#define FXLAB_ID_SPRITE_STORM_SPARK						99

#define FXLAB_ID_SPRITE_MOVIE_CLOUDS					100
#define FXLAB_ID_SPRITE_QUAD_SPARK						101

#define FXLAB_ID_SPRITE_MOVIE_SPARK						102

#define FXLAB_ID_SPRITE_MOVIE_BUBBLE					103

#define FXLAB_ID_SPRITE_MOVIE_TREE_FIRE					104

#define FXLAB_ID_SPRITE_CHARACTER_BUBBLE				105

#define FXLAB_ID_SPRITE_BOSS_STEAM						106

#define FXLAB_ID_SPRITE_BOSS_SMOKE						107

#define FXLAB_ID_SPRITE_WATERFALL_FOG					108

#define FXLAB_ID_SPRITE_BOSS_WATER						109

#define FXLAB_ID_SPRITE_CHARACTER_WORLD_BURST			110

#define FXLAB_ID_SPRITE_CHARACTER_WORLD_EXPLOSION		111

#define FXLAB_ID_SPRITE_MOVIE_DRAGON_FIRE				112

#define FXLAB_ID_SPRITE_MOVIE_ROCKET_FIRE				113
#define FXLAB_ID_SPRITE_MOVIE_ROCKET_SMOKE				114


//-------------------WorldSection ---------------------------

//KeyWorld Definition					
#define FXLAB_SCRIPT_WORLD_ID						0
#define FXLAB_SCRIPT_WORLD_TAIL_SIZE				5
#define FXLAB_SCRIPT_WORLD_TEXTURE					6
#define	FXLAB_SCRIPT_WORLD_FOG_ENABLE				8
#define	FXLAB_SCRIPT_WORLD_FOG_COLOR_RED			9
#define	FXLAB_SCRIPT_WORLD_FOG_COLOR_GREEN			10
#define	FXLAB_SCRIPT_WORLD_FOG_COLOR_BLUE			11
#define	FXLAB_SCRIPT_WORLD_FOG_NEAR					12
#define	FXLAB_SCRIPT_WORLD_FOG_FAR					13
#define FXLAB_SCRIPT_WORLD_TRACK_INFO				14

#define FXLAB_SCRIPT_WORLD_TEXTURE_NAME				0
#define FXLAB_SCRIPT_WORLD_TEXTURE_REFLECTION		1
#define FXLAB_SCRIPT_WORLD_TEXTURE_SCALE			2
#define	FXLAB_SCRIPT_WORLD_TEXTURE_VELOCITY_X		3
#define	FXLAB_SCRIPT_WORLD_TEXTURE_VELOCITY_Y		4

#define FXLAB_SCRIPT_TRACK_ROOT						0
#define FXLAB_SCRIPT_TRACK_DUST_STYLE				1
#define FXLAB_SCRIPT_TRACK_WAVE_RED					2
#define FXLAB_SCRIPT_TRACK_WAVE_GREEN				3
#define FXLAB_SCRIPT_TRACK_WAVE_BLUE				4
#define FXLAB_SCRIPT_TRACK_WAVE_ALPHA				5

#define FXLAB_SCRIPT_WATER_COLOR					6
#define FXLAB_SCRIPT_WATER_DELTA_COLOR				7
#define FXLAB_SCRIPT_WATER_DELTA_HEIGHT				8
#define FXLAB_SCRIPT_WATER_DELTA_UV					9
#define FXLAB_SCRIPT_WORLD_REFLECTION_ENABLE		10


#define FXLAB_WORLD_MOUNTAIN	0
#define FXLAB_WORLD_WATER		1
#define FXLAB_WORLD_FOREST		2
#define FXLAB_WORLD_3			3
#define FXLAB_WORLD_LAVA		4
#define FXLAB_WORLD_5			5			
#define	FXLAB_WORLD_6			6
#define	FXLAB_WORLD_7			7
#define FXLAB_WORLD_CLOCK		8
#define FXLAB_WORLD_9			9
#define FXLAB_WORLD_10			10
#define FXLAB_WORLD_11			11
#define FXLAB_WORLD_12			12
#define FXLAB_WORLD_13			13
#define FXLAB_WORLD_14			14
#define FXLAB_WORLD_15			15
#define FXLAB_WORLD_16			16
#define FXLAB_WORLD_17			17
#define FXLAB_WORLD_18			18
#define FXLAB_WORLD_19			19
#define FXLAB_WORLD_20			20


//--------------------------------------------

//TextureDefinition
#define FXLAB_ID_IMAGE_SPHERE	0
#define FXLAB_ID_IMAGE_STAR4	1
#define FXLAB_ID_IMAGE_STAR6	2
#define FXLAB_ID_IMAGE_STAR8	3
#define FXLAB_ID_IMAGE_STAR83	4
#define FXLAB_ID_IMAGE_STAR12S	5
#define FXLAB_ID_IMAGE_STAR4S	6
#define FXLAB_ID_IMAGE_STAR5S	7
#define FXLAB_ID_IMAGE_BUBBLE   8
//----------------------------------------------------------
//Key Definition

//CheckPoints
#define FXLAB_ID_KEY_CHECKPOINT0			0
#define FXLAB_ID_KEY_CHECKPOINT1			1
#define FXLAB_ID_KEY_CHECKPOINT2			2
#define FXLAB_ID_KEY_CHECKPOINT3			3
#define FXLAB_ID_KEY_CHECKPOINT4			4
#define FXLAB_ID_KEY_CHECKPOINT5			5
#define FXLAB_ID_KEY_CHECKPOINT6			6
#define FXLAB_ID_KEY_CHECKPOINT7			7
#define FXLAB_ID_KEY_CHECKPOINT8			8
#define FXLAB_ID_KEY_CHECKPOINT9			9

#define FXLAB_ID_KEY_POLAR_STAR				10

//Bonuses
#define FXLAB_ID_KEY_TAKE_BONUS_POSITION		11
#define FXLAB_ID_KEY_TAKE_BONUS_VELOCITY		12
#define FXLAB_ID_KEY_TAKE_BONUS_CHARGE			13
#define FXLAB_ID_KEY_TAKE_BONUS_JUMP			14
#define FXLAB_ID_KEY_TAKE_BONUS_NITRO			15
#define FXLAB_ID_KEY_TAKE_BONUS_MANA			16
#define FXLAB_ID_KEY_TAKE_BONUS_STARS			17

#define FXLAB_ID_KEY_BONUS_MODEL_CHARGE			18
#define FXLAB_ID_KEY_BONUS_MODEL_JUMP			19
#define FXLAB_ID_KEY_BONUS_MODEL_NITRO			20
#define FXLAB_ID_KEY_BONUS_MODEL_MANA			21
#define FXLAB_ID_KEY_BONUS_MODEL_STARS			22
#define FXLAB_ID_KEY_BONUS_MODEL_PART			23

#define FXLAB_ID_KEY_CORE_TAKE_BONUS_CHARGE		24
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_JUMP		25
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_NITRO		26
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_MANA		27
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_STARS		28

//WaterWorld::FishWater
#define FXLAB_ID_KEY_FISHWATER_POSITION			29
#define FXLAB_ID_KEY_FISHWATER_VELOCITY			30
#define FXLAB_ID_KEY_FISHWATER_STREAM			31
#define FXLAB_ID_KEY_FISHWATER_CLUSTER			32
#define FXLAB_ID_KEY_CORE_FISHWATER				33

//WaterWorld::WaterPump
#define FXLAB_ID_KEY_WATERPUMP_POSITION			34
#define FXLAB_ID_KEY_WATERPUMP_VELOCITY			35
#define FXLAB_ID_KEY_WATERPUMP_STREAM			36
#define FXLAB_ID_KEY_CORE_WATERPUMP				37

//FireWorld::DragonFire
#define FXLAB_ID_KEY_DRAGON_FIRE_POSITION		38
#define FXLAB_ID_KEY_DRAGON_FIRE_VELOCITY		39
#define FXLAB_ID_KEY_DRAGON_FIRE				40
#define FXLAB_ID_KEY_CORE_DRAGON_FIRE			41
#define FXLAB_ID_KEY_DRAGON_FIRE_SWITCHER		42
#define FXLAB_ID_KEY_DRAGON_FIRE_DAMAGE			43

//ForestWorld::WildClaw
#define FXLAB_ID_KEY_CLAW_SNAKE					44
#define FXLAB_ID_KEY_WILD_CLAW					45
#define FXLAB_ID_KEY_WILD_CLAW_CONTROL			46
#define FXLAB_ID_KEY_CORE_WILD_CLAW				47

//WaterWorld::Cannon
#define FXLAB_ID_KEY_CANNON_DUST_POSITION		48
#define FXLAB_ID_KEY_CANNON_DUST_VELOCITY		49
#define FXLAB_ID_KEY_CANNON_DUST				50
#define FXLAB_ID_KEY_CORE_CANNON_DUST			51

#define FXLAB_ID_KEY_CANNON_FIRE_POSITION		52
#define FXLAB_ID_KEY_CANNON_FIRE_VELOCITY		53
#define FXLAB_ID_KEY_CANNON_FIRE				54

#define FXLAB_ID_KEY_CANNON_OMNI				55

#define FXLAB_ID_KEY_CANNON_BULLET_POSITION		56
#define FXLAB_ID_KEY_CANNON_BULLET_VELOCITY		57
#define FXLAB_ID_KEY_CANNON_BULLET				58
#define FXLAB_ID_KEY_CANNON_BULLET_LINK			59


//Explosion
#define FXLAB_ID_KEY_CORE_EXPLOSION_FIRE				60

#define FXLAB_ID_KEY_BOMB_EXPLOSION_TAIL_POSITION		61
#define FXLAB_ID_KEY_BOMB_EXPLOSION_TAIL_VELOCITY		62
#define FXLAB_ID_KEY_BOMB_EXPLOSION_TAIL				63
#define FXLAB_ID_KEY_BOMB_EXPLOSION_TAIL_LINK			64
#define FXLAB_ID_KEY_BOMB_EXPLOSION_OMNI				65
#define FXLAB_ID_KEY_BOMB_EXPLOSION_SHOCK_WAVE			66
#define FXLAB_ID_KEY_BOMB_EXPLOSION_CLIENT_SET			67
#define FXLAB_ID_KEY_BOMB_EXPLOSION_LINK				68
#define FXLAB_ID_KEY_BOMB_EXPLOSION						69

#define FXLAB_ID_KEY_STONE_EXPLOSION_SMOKE_POSITION		70
#define FXLAB_ID_KEY_STONE_EXPLOSION_SMOKE_VELOCITY		71
#define FXLAB_ID_KEY_STONE_EXPLOSION_SMOKE				72
#define FXLAB_ID_KEY_STONE_EXPLOSION_OMNI				73
#define	FXLAB_ID_KEY_STONE_EXPLOSION_CLIENT_SET			74
#define	FXLAB_ID_KEY_STONE_EXPLOSION_LINK				75
#define	FXLAB_ID_KEY_STONE_EXPLOSION					76

#define FXLAB_ID_KEY_FIRE_EXPLOSION_SMOKE_POSITION		77
#define FXLAB_ID_KEY_FIRE_EXPLOSION_SMOKE_VELOCITY		78
#define FXLAB_ID_KEY_FIRE_EXPLOSION_SMOKE				79
#define FXLAB_ID_KEY_FIRE_EXPLOSION_OMNI				80
#define FXLAB_ID_KEY_FIRE_EXPLOSION_CLIENT_SET			81
#define FXLAB_ID_KEY_FIRE_EXPLOSION_LINK				82
#define FXLAB_ID_KEY_FIRE_EXPLOSION						83

//Vocano
#define FXLAB_ID_KEY_VOLCANIC_STONE_TAIL_LINK			84
#define FXLAB_ID_KEY_VOLCANIC_LAUNCHER					85

#define FXLAB_ID_KEY_VOLCANIC_FIRE_POSITION				86
#define FXLAB_ID_KEY_VOLCANIC_FIRE_VELOCITY				87
#define FXLAB_ID_KEY_VOLCANIC_FIRE						88
#define FXLAB_ID_KEY_CORE_VOLCANIC_FIRE					89

#define FXLAB_ID_KEY_VOLCANIC_DUST_POSITION				90
#define FXLAB_ID_KEY_VOLCANIC_DUST_VELOCITY				91
#define FXLAB_ID_KEY_VOLCANIC_DUST						92
#define FXLAB_ID_KEY_CORE_VOLCANIC_DUST					93

#define FXLAB_ID_KEY_VOLCANIC_OMNI						94

#define FXLAB_ID_KEY_VOLCANIC_STONE_TAIL_POSITION		95
#define FXLAB_ID_KEY_VOLCANIC_STONE_TAIL_VELOCITY		96
#define FXLAB_ID_KEY_VOLCANIC_STONE_TAIL				97
#define FXLAB_ID_KEY_CORE_VOLCANIC_STONE_FIRE			98

#define FXLAB_ID_KEY_HEAD_LAUNCHER						99

//HeadFireSystem
#define FXLAB_ID_KEY_HEAD_FIRE_DAMAGE					100
#define FXLAB_ID_KEY_HEAD_ROSE_DAMAGE					101

//FireRose
#define FXLAB_ID_KEY_CORE_ROSE_FIRE						102
#define FXLAB_ID_KEY_ROSE_FIRE_POSITION					103
#define FXLAB_ID_KEY_ROSE_FIRE_VELOCITY					104
#define FXLAB_ID_KEY_ROSE_FIRE							105
#define FXLAB_ID_KEY_ROSE_FIRE_OMNI						106
#define FXLAB_ID_KEY_ROSE_FIRE_SET						107
#define FXLAB_ID_KEY_ROSE_FIRE_SWITCHER					108

//HeadBreath
#define FXLAB_ID_KEY_HEAD_BREATH_POSITION				109
#define FXLAB_ID_KEY_HEAD_BREATH_VELOCITY				110
#define FXLAB_ID_KEY_HEAD_BREATH						111
#define FXLAB_ID_KEY_HEAD_BREATH_LAUNCHER				112
#define FXLAB_ID_KEY_CORE_HEAD_BREATH					113

//LavaWind
#define FXLAB_ID_KEY_LAVA_WIND_POSITION					114
#define FXLAB_ID_KEY_LAVA_WIND_VELOCITY					115
#define FXLAB_ID_KEY_LAVA_WIND							116
#define FXLAB_ID_KEY_LAVA_WIND_LAUNCHER					117
#define FXLAB_ID_KEY_CORE_LAVA_WIND						118

//WaterBubbleFlux
#define FXLAB_ID_KEY_WATER_BUBBLE_FLUX_POSITION			119
#define FXLAB_ID_KEY_WATER_BUBBLE_FLUX_VELOCITY			120
#define FXLAB_ID_KEY_WATER_BUBBLE_FLUX					121
#define FXLAB_ID_KEY_WATER_FIELD_STREAM					122
#define FXLAB_ID_KEY_CORE_WATER_BUBBLE_FLUX				123

//ForestBubbleFlux
#define FXLAB_ID_KEY_FOREST_BUBBLE_FLUX_POSITION		124
#define FXLAB_ID_KEY_FOREST_BUBBLE_FLUX_VELOCITY		125
#define FXLAB_ID_KEY_FOREST_BUBBLE_FLUX					126
#define FXLAB_ID_KEY_FOREST_FIELD_STREAM				127
#define FXLAB_ID_KEY_CORE_FOREST_BUBBLE_FLUX			128

//StoneFlux
#define FXLAB_ID_KEY_STONE_BUBBLE_FLUX_POSITION			129
#define FXLAB_ID_KEY_STONE_BUBBLE_FLUX_VELOCITY			130
#define FXLAB_ID_KEY_STONE_BUBBLE_FLUX					131
#define FXLAB_ID_KEY_STONE_FIELD_STREAM					132
#define FXLAB_ID_KEY_CORE_STONE_BUBBLE_FLUX				133

//Altar
#define FXLAB_ID_KEY_ALTAR_FIRE_POSITION				134
#define FXLAB_ID_KEY_ALTAR_FIRE_VELOCITY				135
#define FXLAB_ID_KEY_ALTAR_FIRE							136
#define FXLAB_ID_KEY_CORE_ALTAR_FIRE					137
#define FXLAB_ID_KEY_ALTAR_DAMAGE						138

#define FXLAB_ID_KEY_ALTAR_DUST_POSITION				139
#define FXLAB_ID_KEY_ALTAR_DUST_VELOCITY				140
#define FXLAB_ID_KEY_ALTAR_DUST							141
#define FXLAB_ID_KEY_CORE_ALTAR_DUST					142

//StoneHead
#define FXLAB_ID_KEY_HEAD_STREAM_POSITION				143
#define FXLAB_ID_KEY_HEAD_STREAM_VELOCITY				144
#define FXLAB_ID_KEY_HEAD_STREAM						145
#define FXLAB_ID_KEY_CORE_HEAD_STREAM					146

//PlasmaClaw
#define FXLAB_ID_KEY_PLASMA_CLAW_CONTROL				147

//BowMachine
#define FXLAB_ID_KEY_BOW_MACHINE_ACTIVE_LIGHTNING		148
#define FXLAB_ID_KEY_BOW_MACHINE_PASSIVE_LIGHTNING		149
#define FXLAB_ID_KEY_BOW_MACHINE_ACTIVE_OMNI			150
#define	FXLAB_ID_KEY_BOW_MACHINE_PASSIVE_OMNI			151
#define FXLAB_ID_KEY_BOW_MACHINE						152
#define FXLAB_ID_KEY_BOW_MACHINE_DAMAGE					153

//ShaftMachine
#define FXLAB_ID_KEY_SHAFT_MACHINE_LIGHTNING			154
#define FXLAB_ID_KEY_SHAFT_MACHINE_OMNI					155
#define FXLAB_ID_KEY_SHAFT_MACHINE_DAMAGE				156
#define FXLAB_ID_KEY_SHAFT_MACHINE_LINK					157

//BallWind
#define FXLAB_ID_KEY_BALL_WIND_ACTIVE_FIRE_POSITION		158
#define FXLAB_ID_KEY_BALL_WIND_ACTIVE_FIRE_VELOCITY		159
#define FXLAB_ID_KEY_BALL_WIND_ACTIVE_FIRE				160

#define FXLAB_ID_KEY_BALL_WIND_PASSIVE_FIRE_POSITION	161
#define FXLAB_ID_KEY_BALL_WIND_PASSIVE_FIRE_VELOCITY	162
#define FXLAB_ID_KEY_BALL_WIND_PASSIVE_FIRE				163

#define FXLAB_ID_KEY_BALL_WIND_LEFT_LINK				164
#define FXLAB_ID_KEY_BALL_WIND_RIGHT_LINK				165

#define FXLAB_ID_KEY_CORE_BALLWIND_PASSIVE				166
#define FXLAB_ID_KEY_CORE_BALLWIND_ACTIVE				167

//Suicide
#define FXLAB_ID_KEY_CORE_SUICIDE_FIRE					168
#define FXLAB_ID_KEY_SUICIDE_FIRE_POSITION				169
#define FXLAB_ID_KEY_SUICIDE_FIRE_VELOCITY				170
#define FXLAB_ID_KEY_SUICIDE_FIRE						171
#define FXLAB_ID_KEY_SUICIDE_LINK						172

//Clown
#define	FXLAB_ID_KEY_CLOWN_POSITION						173
#define	FXLAB_ID_KEY_CLOWN_VELOCITY						174
#define	FXLAB_ID_KEY_CLOWN								175

#define FXLAB_ID_KEY_CORE_CLOWN_RED						176
#define FXLAB_ID_KEY_CORE_CLOWN_ORANGE					177
#define FXLAB_ID_KEY_CORE_CLOWN_YELLOW					178
#define FXLAB_ID_KEY_CORE_CLOWN_GREEN					179
#define FXLAB_ID_KEY_CORE_CLOWN_LIGHT_BLUE				180
#define FXLAB_ID_KEY_CORE_CLOWN_BLUE					181
#define FXLAB_ID_KEY_CORE_CLOWN_MAGENTA					182

//Tomato
#define FXLAB_ID_KEY_CORE_TOMATO						183
#define FXLAB_ID_KEY_TOMATO_BURST_POSITION				184
#define FXLAB_ID_KEY_TOMATO_BURST_VELOCITY				185
#define FXLAB_ID_KEY_TOMATO_BURST						186

//FireBall
#define FXLAB_ID_KEY_CORE_FIREBALL						187
#define FXLAB_ID_KEY_FIREBALL_TAIL_POSITION				188
#define FXLAB_ID_KEY_FIREBALL_TAIL_VELOCITY				189
#define FXLAB_ID_KEY_FIREBALL_TAIL						190
#define FXLAB_ID_KEY_FIREBALL_LIGHT						191
#define FXLAB_ID_KEY_FIREBALL_SET						192
#define FXLAB_ID_KEY_FIREBALL_LINK						193

#define FXLAB_ID_KEY_SERVER_FIREBALL_LINK				194
#define FXLAB_ID_KEY_SERVER_FIREBALL_DAMAGE				195

//LighningBolt
#define FXLAB_ID_KEY_LIGHTNING_BOLT_BOW					196
#define FXLAB_ID_KEY_LIGHTNING_BOLT_LIGHT				197
#define FXLAB_ID_KEY_LIGHTNING_BOLT_LINK				198

#define FXLAB_ID_KEY_CORE_LIGHTNING_BOLT_SPARK			199
#define FXLAB_ID_KEY_LIGHTNING_BOLT_SPARK_POSITION		200
#define FXLAB_ID_KEY_LIGHTNING_BOLT_SPARK_VELOCITY		201
#define FXLAB_ID_KEY_LIGHTNING_BOLT_SPARK				202

#define FXLAB_ID_KEY_SERVER_LIGHTNING_BOLT_LINK			203
#define FXLAB_ID_KEY_SERVER_LIGHTNING_BOLT_DAMAGE		204

//FireStone
#define FXLAB_ID_KEY_SERVER_FIRE_STONE_LINK				205
#define FXLAB_ID_KEY_SERVER_FIRE_STONE_DAMAGE			206
#define FXLAB_ID_KEY_FIRE_STONE_TAIL_LINK				207

//SnowFall
#define FXLAB_ID_KEY_CORE_SNOW_FALL						208
#define FXLAB_ID_KEY_CORE_SNOW_CLOUDS					209

#define FXLAB_ID_KEY_SNOW_FALL_EXPLOSION_POSITION		210
#define FXLAB_ID_KEY_SNOW_FALL_EXPLOSION_VELOCITY		211
#define FXLAB_ID_KEY_SNOW_FALL_EXPLOSION				212

#define FXLAB_ID_KEY_SNOW_FALL_TAIL_POSITION			213
#define FXLAB_ID_KEY_SNOW_FALL_TAIL_VELOCITY			214
#define FXLAB_ID_KEY_SNOW_FALL_TAIL						215

#define FXLAB_ID_KEY_SNOW_CLOUDS						216

#define FXLAB_ID_KEY_SNOW_FALL_LINK						217

//ElectricStorm
#define FXLAB_ID_KEY_CORE_STORM_CLOUDS					218

#define FXLAB_ID_KEY_ELECTRIC_STORM_BOW					219
#define FXLAB_ID_KEY_ELECTRIC_STORM_LIGHT				220
#define FXLAB_ID_KEY_ELECTRIC_STORM_DAMAGE				221
#define FXLAB_ID_KEY_STORM_CLOUDS						222

//FireGarden
#define FXLAB_ID_KEY_FIRE_GARDEN_DAMAGE					223

//WormSlimes
#define FXLAB_ID_KEY_WORM_GREEN_SLIME_MODEL				224
#define FXLAB_ID_KEY_WORM_GREEN_SLIME_CIRCLE			225
#define FXLAB_ID_KEY_WORM_GREEN_SLIME_BODY				226

#define FXLAB_ID_KEY_WORM_YELLOW_SLIME_MODEL			227
#define FXLAB_ID_KEY_WORM_YELLOW_SLIME_CIRCLE			228
#define FXLAB_ID_KEY_WORM_YELLOW_SLIME_BODY				229

//RageSlime
#define FXLAB_ID_KEY_RAGE_SLIME_MODEL					230
#define FXLAB_ID_KEY_RAGE_SLIME_CIRCLE					231

//Fury Fungus
#define FXLAB_ID_KEY_FURY_FUNGUS_FOG_POSITION			232
#define FXLAB_ID_KEY_FURY_FUNGUS_FOG_VELOCITY			233
#define FXLAB_ID_KEY_FURY_FUNGUS_FOG					234
#define FXLAB_ID_KEY_CORE_FURY_FUNGUS_FOG				235

#define FXLAB_ID_KEY_FURY_FUNGUS_LASH					236
#define FXLAB_ID_KEY_FURY_FUNGUS_CIRCLE					237

//VoodooMaster

#define FXLAB_ID_KEY_VOODOO_HEAD_MODEL					238
#define FXLAB_ID_KEY_VOODOO_HEAD_OMNI					239
#define FXLAB_ID_KEY_VOODOO_MASTER_LINK					240
#define FXLAB_ID_KEY_VOODOO_MASTER_DAMAGE				241
#define FXLAB_ID_KEY_VOODOO_MASTER_BRAIN				242

#define FXLAB_ID_KEY_CORE_VOODOO_HEAD					243
#define FXLAB_ID_KEY_VOODOO_HEAD_TAIL_POSITION			244
#define FXLAB_ID_KEY_VOODOO_HEAD_TAIL_VELOCITY			245
#define FXLAB_ID_KEY_VOODOO_HEAD_TAIL					246

//KineticHit

#define FXLAB_ID_KEY_KINETIC_HIT_WAVE					247
#define FXLAB_ID_KEY_KINETIC_HIT_DEFORMATION			248
#define FXLAB_ID_KEY_KINETIC_HIT_DAMAGE					249

//Electric Spark
#define FXLAB_ID_KEY_CORE_LIGHTNING_SPARK				250
#define FXLAB_ID_KEY_LIGHTNING_SPARK_POSITION			251
#define FXLAB_ID_KEY_LIGHTNING_SPARK_VELOCITY			252
#define FXLAB_ID_KEY_LIGHTNING_SPARK					253

//Spike								 
#define FXLAB_ID_KEY_CORE_SPIKE_BURST					254
#define FXLAB_ID_KEY_SPIKE_BURST_POSITION				255
#define FXLAB_ID_KEY_SPIKE_BURST_VELOCITY				256
#define FXLAB_ID_KEY_SPIKE_BURST						257

//Revolt 
#define FXLAB_ID_KEY_REVOLT_SPACE_MODEL					258
#define FXLAB_ID_KEY_REVOLT_SPACE_LINK					259

//MassShifter
#define FXLAB_ID_KEY_PRIMARY_MASS_SHIFTER				260
#define FXLAB_ID_KEY_SECONDARY_MASS_SHIFTER				261
#define FXLAB_ID_KEY_MASS_SHIFTER_MODEL					262

//Charge
#define FXLAB_ID_KEY_CORE_CHARGE_ENERGY					263
#define FXLAB_ID_KEY_CHARGE_ENERGY_POSITION				264
#define FXLAB_ID_KEY_CHARGE_ENERGY_VELOCITY				265
#define FXLAB_ID_KEY_CHARGE_ENERGY						266
#define FXLAB_ID_KEY_CHARGE_ENERGY_IMPULSE_LINK			267
#define FXLAB_ID_KEY_CHARGE_ENERGY_CYCLE_LINK			268

#define FXLAB_ID_KEY_CORE_CHARGE_MANA					269
#define FXLAB_ID_KEY_CHARGE_MANA_POSITION				270
#define FXLAB_ID_KEY_CHARGE_MANA_VELOCITY				271
#define FXLAB_ID_KEY_CHARGE_MANA						272
#define FXLAB_ID_KEY_CHARGE_MANA_IMPULSE_LINK			273
#define FXLAB_ID_KEY_CHARGE_MANA_CYCLE_LINK				274

//Actions
#define FXLAB_ID_KEY_CORE_JUMP_ACTION					275
#define FXLAB_ID_KEY_JUMP_ACTION_POSITION				276
#define FXLAB_ID_KEY_JUMP_ACTION_VELOCITY				277
#define FXLAB_ID_KEY_JUMP_ACTION						278
#define FXLAB_ID_KEY_JUMP_ACTION_LINK					279

#define FXLAB_ID_KEY_CORE_NITRO_ACTION					280
#define FXLAB_ID_KEY_NITRO_ACTION_POSITION				281
#define FXLAB_ID_KEY_NITRO_ACTION_VELOCITY				282
#define FXLAB_ID_KEY_NITRO_ACTION						283
#define FXLAB_ID_KEY_NITRO_ACTION_LINK					284

//ChargePlace
#define FXLAB_ID_KEY_CORE_PLACE_ENERGY_FOG				285
#define FXLAB_ID_KEY_CORE_PLACE_ENERGY_STAR				286
#define FXLAB_ID_KEY_PLACE_ENERGY_POSITION				287
#define FXLAB_ID_KEY_PLACE_ENERGY_VELOCITY				288
#define FXLAB_ID_KEY_PLACE_ENERGY_FOG					289
#define FXLAB_ID_KEY_PLACE_ENERGY_STAR					290

#define FXLAB_ID_KEY_PLACE_ENERGY_SENSOR				291
#define FXLAB_ID_KEY_PLACE_MANA_SENSOR					292

#define FXLAB_ID_KEY_CORE_PLACE_MANA_STAR				293
#define FXLAB_ID_KEY_PLACE_MANA_POSITION				294
#define FXLAB_ID_KEY_PLACE_MANA_VELOCITY				295
#define FXLAB_ID_KEY_PLACE_MANA							296

//MechosFire
#define FXLAB_ID_KEY_CORE_MECHOS_FIRE					297
#define FXLAB_ID_KEY_MECHOS_FIRE_POSITION				298
#define FXLAB_ID_KEY_MECHOS_FIRE_VELOCITY				299
#define FXLAB_ID_KEY_MECHOS_FIRE						300
#define FXLAB_ID_KEY_MECHOS_FIRE_LINK					301

//MechosBubbles
#define FXLAB_ID_KEY_CORE_MECHOS_BUBBLE					302
#define FXLAB_ID_KEY_MECHOS_BUBBLE_POSITION				303
#define FXLAB_ID_KEY_MECHOS_BUBBLE_VELOCITY				304
#define FXLAB_ID_KEY_MECHOS_BUBBLE						305

//MechosBurn
#define FXLAB_ID_KEY_CORE_MECHOS_BURN					306
#define FXLAB_ID_KEY_MECHOS_BURN_POSITION				307
#define FXLAB_ID_KEY_MECHOS_BURN_VELOCITY				308
#define FXLAB_ID_KEY_MECHOS_BURN						309
#define FXLAB_ID_KEY_MECHOS_BURN_LINK					310
#define FXLAB_ID_KEY_MECHOS_BURN_SHOCK_WAVE				311
#define FXLAB_ID_KEY_MECHOS_BURN_OMNI					312

//Protection
#define FXLAB_ID_KEY_COLOR_CONTROLLER_ARMOR				313
#define FXLAB_ID_KEY_COLOR_CONTROLLER_SKIN				314
#define FXLAB_ID_KEY_COLOR_CONTROLLER_ISOLATION			315
#define FXLAB_ID_KEY_COLOR_CONTROLLER_PASSAGE			316

//MechosDust
#define FXLAB_ID_KEY_CORE_MECHOS_DUST000				317
#define FXLAB_ID_KEY_MECHOS_DUST_POSITION				318
#define FXLAB_ID_KEY_MECHOS_DUST_VELOCITY				319
#define FXLAB_ID_KEY_MECHOS_DUST000						320

//Teleport
#define FXLAB_ID_KEY_CORE_TELEPORT_BURN					321
#define FXLAB_ID_KEY_TELEPORT_BURN_POSITION				322
#define FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY				323
#define FXLAB_ID_KEY_TELEPORT_BURN						324
#define FXLAB_ID_KEY_TELEPORT_OMNI						325

//LighningSeeds
#define FXLAB_ID_KEY_LIGHTNING_SEEDS_PASSIVE_LIGHTNING	326
#define FXLAB_ID_KEY_LIGHTNING_SEEDS_ACTIVE_LIGHTNING	327
#define FXLAB_ID_KEY_LIGHTNING_SEEDS_PASSIVE_OMNI		328
#define FXLAB_ID_KEY_LIGHTNING_SEEDS_ACTIVE_OMNI		329
#define FXLAB_ID_KEY_LIGHTNING_SEEDS_DAMAGE				330
#define FXLAB_ID_KEY_LIGHTNING_SEEDS					331

//DamageWarning
#define FXLAB_ID_KEY_CORE_DAMAGE_WARNING				332
#define FXLAB_ID_KEY_DAMAGE_WARNING_POSITION			333
#define FXLAB_ID_KEY_DAMAGE_WARNING_VELOCITY			334
#define FXLAB_ID_KEY_DAMAGE_WARNING						335
#define FXLAB_ID_KEY_DAMAGE_WARNING_LINK				336

//WaveEffect
#define FXLAB_ID_KEY_MECHOS_WAVE_MODEL					337

//BubbleRush
#define FXLAB_ID_KEY_CORE_BUBBLE_RUSH					338
#define FXLAB_ID_KEY_BUBBLE_RUSH_POSITION				339
#define FXLAB_ID_KEY_BUBBLE_RUSH_VELOCITY				340
#define FXLAB_ID_KEY_BUBBLE_RUSH_BURST					341

//0-Trap
#define FXLAB_ID_KEY_SHIFT_TRAP_MODEL					342
#define FLXAB_ID_KEY_SHIFT_TRAP_SPHERE					343

//Mines
#define FXLAB_ID_KEY_MINE_DUST_POSITION					344
#define FXLAB_ID_KEY_MINE_DUST_VELOCITY					345
#define FXLAB_ID_KEY_MINE_DUST							346
#define FXLAB_ID_KEY_CORE_MINE_DUST						347
#define FXLAB_ID_KEY_MINE_CLIENT_LINK					348

//Petard

#define FXLAB_ID_KEY_PETARD_MODEL						349

#define FXLAB_ID_KEY_PETARD_TAIL_POSITION				350
#define FXLAB_ID_KEY_PETARD_TAIL_VELOCITY				351
#define FXLAB_ID_KEY_PETARD_TAIL						352

#define FXLAB_ID_KEY_PETARD_BURN_MODEL					353
#define FXLAB_ID_KEY_PETARD_BURN_OMNI					354
#define FXLAB_ID_KEY_PETARD_BURN_POSITION				355
#define FXLAB_ID_KEY_PETARD_BURN_VELOCITY				356
#define FXLAB_ID_KEY_PETARD_BURN						357

#define FXLAB_ID_KEY_PETARD_BOX_TAIL_POSITION			358
#define FXLAB_ID_KEY_PETARD_BOX_TAIL_VELOCITY			359
#define FXLAB_ID_KEY_PETARD_BOX_TAIL					360

#define FXLAB_ID_KEY_PETARD_BONUS_POSITION				361
#define FXLAB_ID_KEY_PETARD_BONUS_VELOCITY				362
#define FXLAB_ID_KEY_PETARD_BONUS						363

#define FXLAB_ID_KEY_MINOR_BONUS_CLIENT_LINK			364
#define FXLAB_ID_KEY_MAJOR_BONUS_CLIENT_LINK			365

//MenuTeleport
#define FXLAB_ID_KEY_SERVER_TELEPORT_MENU				366

#define FXLAB_ID_KEY_CORE_TELEPORT_BURN_LAST			367
#define FXLAB_ID_KEY_TELEPORT_BURN_POSITION_LAST		368
#define FXLAB_ID_KEY_TELEPORT_BURN_VELOCITY_LAST		369
#define FXLAB_ID_KEY_TELEPORT_BURN_LAST					370

//DamageWarning
#define FXLAB_ID_KEY_DAMAGE_WARNING_IMPULSE				371

//LavaAltar
#define FXLAB_ID_KEY_CORE_LAVA_ALTAR_FIRE				372
#define FXLAB_ID_KEY_LAVA_ALTAR_FIRE_POSITION			373
#define FXLAB_ID_KEY_LAVA_ALTAR_FIRE_VELOCITY			374
#define FXLAB_ID_KEY_LAVA_ALTAR_FIRE					375
#define FXLAB_ID_KEY_LAVA_ALTAR_OMNI					376
#define FXLAB_ID_KEY_LAVA_ALTAR_DAMAGE					377

//FireTrack
#define FXLAB_ID_KEY_CORE_SCARLET_TRACK_LINE			378
#define FXLAB_ID_KEY_SCARLET_TRACK_LINE_POSITION		379
#define FXLAB_ID_KEY_SCARLET_TRACK_LINE_VELOCITY		380
#define FXLAB_ID_KEY_SCARLET_TRACK_LINE					381
#define FXLAB_ID_KEY_SCARLET_TRACK_DAMAGE				382

//ArcaneIndicator
#define FXLAB_ID_KEY_ARCANE_INDICATOR					383

//MenuTeleport
#define FXLAB_ID_KEY_MENU_TELEPORT_OMNI					384
#define FXLAB_ID_KEY_MENU_TELEPORT_COLOR_CONTROLLER		385

//Storm
#define FXLAB_ID_KEY_ELECTRIC_STORM_MARKER_OMNI			386

//StoneDust
#define FXLAB_ID_KEY_CORE_STONE_DUST					387
#define FXLAB_ID_KEY_STONE_DUST_POSITION				388
#define FXLAB_ID_KEY_STONE_DUST_VELOCITY				389
#define FXLAB_ID_KEY_STONE_DUST							390

//BlueSlime
#define FXLAB_ID_KEY_BLUE_SLIME_MODEL					391
#define FXLAB_ID_KEY_BLUE_SLIME_CIRCLE					392

//SnowLayer
#define FXLAB_ID_KEY_CORE_SNOW_LAYER					393
#define FXLAB_ID_KEY_SNOW_LAYER_POSITION				394
#define FXLAB_ID_KEY_SNOW_LAYER_VELOCITY				395
#define FXLAB_ID_KEY_SNOW_LAYER							396

//BioPower
#define FXLAB_ID_KEY_COLOR_CONTROLLER_BIO				397

//TownDust
#define FXLAB_ID_KEY_CORE_MECHOS_DUST302				398
#define FXLAB_ID_KEY_MECHOS_DUST302						399
								 
#define FXLAB_ID_KEY_CORE_MECHOS_DUST303				400
#define FXLAB_ID_KEY_MECHOS_DUST303						401

#define FXLAB_ID_KEY_CORE_MECHOS_DUST305				402
#define FXLAB_ID_KEY_MECHOS_DUST305						403

//LavaDust
#define FXLAB_ID_KEY_CORE_MECHOS_DUST400				404
#define FXLAB_ID_KEY_MECHOS_DUST400						405

#define FXLAB_ID_KEY_CORE_MECHOS_DUST402				406
#define FXLAB_ID_KEY_MECHOS_DUST402						407

#define FXLAB_ID_KEY_CORE_MECHOS_DUST412				408
#define FXLAB_ID_KEY_MECHOS_DUST412						409

//WaterDust
#define FXLAB_ID_KEY_CORE_MECHOS_DUST100				410
#define FXLAB_ID_KEY_MECHOS_DUST100						411

#define FXLAB_ID_KEY_CORE_MECHOS_DUST102				412
#define FXLAB_ID_KEY_MECHOS_DUST102						413

#define FXLAB_ID_KEY_CORE_MECHOS_DUST142				414
#define FXLAB_ID_KEY_MECHOS_DUST142						415

//ForestDust
//0
#define FXLAB_ID_KEY_CORE_MECHOS_DUST200				416
#define FXLAB_ID_KEY_MECHOS_DUST200						417

#define FXLAB_ID_KEY_CORE_MECHOS_DUST202				418
#define FXLAB_ID_KEY_MECHOS_DUST202						419

#define FXLAB_ID_KEY_CORE_MECHOS_DUST207				420
#define FXLAB_ID_KEY_MECHOS_DUST207						421

//1
#define FXLAB_ID_KEY_CORE_MECHOS_DUST210				422
#define FXLAB_ID_KEY_MECHOS_DUST210						423

#define FXLAB_ID_KEY_CORE_MECHOS_DUST212				424
#define FXLAB_ID_KEY_MECHOS_DUST212						425

//2
#define FXLAB_ID_KEY_CORE_MECHOS_DUST220				426
#define FXLAB_ID_KEY_MECHOS_DUST220						427

#define FXLAB_ID_KEY_CORE_MECHOS_DUST222				428
#define FXLAB_ID_KEY_MECHOS_DUST222						429

#define FXLAB_ID_KEY_CORE_MECHOS_DUST227				430
#define FXLAB_ID_KEY_MECHOS_DUST227						431

//3
#define FXLAB_ID_KEY_CORE_MECHOS_DUST230				432
#define FXLAB_ID_KEY_MECHOS_DUST230						433

#define FXLAB_ID_KEY_CORE_MECHOS_DUST232				434
#define FXLAB_ID_KEY_MECHOS_DUST232						435

#define FXLAB_ID_KEY_CORE_MECHOS_DUST237				436
#define FXLAB_ID_KEY_MECHOS_DUST237						437

//4
#define FXLAB_ID_KEY_CORE_MECHOS_DUST240				438
#define FXLAB_ID_KEY_MECHOS_DUST240						439

#define FXLAB_ID_KEY_CORE_MECHOS_DUST242				440
#define FXLAB_ID_KEY_MECHOS_DUST242						441

//JumpAction
#define FXLAB_ID_KEY_JUMP_ACTION_MODEL					442
#define FXLAB_ID_KEY_JUMP_ACTION_TRACK					443

//WhiteStoneDust
#define FXLAB_ID_KEY_CORE_WHITE_STONE_DUST				444
#define FXLAB_ID_KEY_STONE_WHITE_DUST					445

//NitroAction
#define FXLAB_ID_KEY_NITRO_ACTION_MODEL					446
#define FXLAB_ID_KEY_NITRO_ACTION_TRACK					447

//TakeBonusProtection

#define FXLAB_ID_KEY_TAKE_BONUS_PROTECTION_FIRE				448
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_PROTECTION_FIRE		449

#define FXLAB_ID_KEY_TAKE_BONUS_PROTECTION_ELECTRIC			450
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_PROTECTION_ELECTRIC	451

#define FXLAB_ID_KEY_TAKE_BONUS_PROTECTION_ARMOR			452
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_PROTECTION_ARMOR		453

#define FXLAB_ID_KEY_TAKE_BONUS_PROTECTION_BIO				454
#define FXLAB_ID_KEY_CORE_TAKE_BONUS_PROTECTION_BIO			455

//Interface Teleportation Spot
#define FXLAB_ID_KEY_TELEPORT_MENU_ACTIVE_MODEL				456
#define FXLAB_ID_KEY_TELEPORT_MENU_PASSIVE_MODEL			457

//MassShifter Nitro
#define FXLAB_ID_KEY_MASS_SHIFTER_MODEL_NITRO				458
#define FXLAB_ID_KEY_TELEPORT_OMNI_NITRO					459

//SnowFallExplosion
#define FXLAB_ID_KEY_CORE_SNOW_FALL_EXPLOSION				460
#define FXLAB_ID_KEY_SNOW_BULLET_MODEL						461

#define FXLAB_ID_KEY_CORE_SNOW_BULLET						462
#define FXLAB_ID_KEY_SNOW_BULLET_POSITION					463
#define FXLAB_ID_KEY_SNOW_BULLET_VELOCITY					464
#define FXLAB_ID_KEY_SNOW_BULLET							465

//FireClouds
#define FXLAB_ID_KEY_CORE_FIRE_CLOUDS						466
#define FXLAB_ID_KEY_FIRE_CLOUDS							467
#define FXLAB_ID_KEY_FIRE_BULLET_MODEL						468

#define FXLAB_ID_KEY_CORE_FIRE_BULLET						469
#define FXLAB_ID_KEY_FIRE_BULLET_POSITION					470
#define FXLAB_ID_KEY_FIRE_BULLET_VELOCITY					471
#define FXLAB_ID_KEY_FIRE_BULLET							472

//World Irradiate
#define FXLAB_ID_KEY_WORLD_IRRADIATE_DEFORMATION			473
#define FXLAB_ID_KEY_WORLD_IRRADIATE_WAVE					474
#define FXLAB_ID_KEY_WORLD_IRRADIATE_OMNI					475
#define FXLAB_ID_KEY_WORLD_IRRADIATE						476

//LightningDamage
#define FXLAB_ID_KEY_COLOR_CONTROLLER_LIGHTNING_DAMAGE		477

//FireBonus
#define FXLAB_ID_KEY_CORE_BONUS_FIRE						478
#define FXLAB_ID_KEY_BONUS_FIRE_POSITION					479
#define FXLAB_ID_KEY_BONUS_FIRE_VELOCITY					480
#define FXLAB_ID_KEY_BONUS_FIRE								481
#define FXLAB_ID_KEY_BONUS_FIRE_OMNI						482

//CSharacter Shifter
#define FXLAB_ID_KEY_PRIMARY_MASS_SHIFTER_CHARACTER			483
#define FXLAB_ID_KEY_SECONDARY_MASS_SHIFTER_CHARACTER		484
#define FXLAB_ID_KEY_MASS_SHIFTER_MODEL_CHARACTER			485
#define FXLAB_ID_KEY_TELEPORT_OMNI_CHARACTER				486

//Dragon Rose
#define FXLAB_ID_KEY_DRAGON_ROSE_DAMAGE			487
#define FXLAB_ID_KEY_DRAGON_ROSE_POSITION		488
#define FXLAB_ID_KEY_DRAGON_ROSE_VELOCITY		489
#define FXLAB_ID_KEY_DRAGON_ROSE				    490
#define FXLAB_ID_KEY_CORE_DRAGON_ROSE				491
#define FXLAB_ID_KEY_DRAGON_ROSE_OMNI				492
#define FXLAB_ID_KEY_DRAGON_ROSE_SET				493

//Spline Way
#define FXLAB_ID_KEY_CORE_SPLINE_WAY			494

//Frozen Effect
#define FXLAB_ID_KEY_COLOR_CONTROLLER_FROZEN	495
  
//FireMovie
#define FXLAB_ID_KEY_MOVIE_HEAD_FIRE_POSITION	496
#define FXLAB_ID_KEY_MOVIE_HEAD_FIRE_VELOCITY	497
#define FXLAB_ID_KEY_MOVIE_HEAD_FIRE			498
#define FXLAB_ID_KEY_CORE_MOVIE_HEAD_FIRE		499
#define FXLAB_ID_KEY_MOVIE_HEAD_SET				500

//LightningTest
#define FXLAB_ID_KEY_MOVIE_LIGHTNING_TEST		501

//MovieStorm
#define FXLAB_ID_KEY_MOVIE_STORM_BOW			502
#define FXLAB_ID_KEY_MOVIE_STORM_LIGHT			503
#define FXLAB_ID_KEY_MOVIE_STORM_CONTROL		504

//Movie Wave
#define FXLAB_ID_KEY_MOVIE_WAVE_CONTROL			505

//Movie Spray
#define FXLAB_ID_KEY_MOVIE_SPRAY_POSITION		506
#define FXLAB_ID_KEY_MOVIE_SPRAY_VELOCITY		507
#define FXLAB_ID_KEY_MOVIE_SPRAY_STREAM			508
#define FXLAB_ID_KEY_CORE_MOVIE_SPRAY			509

//Movie Sparks
#define FXLAB_ID_KEY_MOVIE_SPARK_POSITION		510
#define FXLAB_ID_KEY_MOVIE_SPARK_VELOCITY		511
#define FXLAB_ID_KEY_MOVIE_SPARK				512

//Storm Sparks
#define FXLAB_ID_KEY_CORE_STORM_SPARK			513
#define FXLAB_ID_KEY_STORM_SPARK_POSITION		514
#define FXLAB_ID_KEY_STORM_SPARK_VELOCITY		515
#define FXLAB_ID_KEY_STORM_SPARK				516

//Movie Clouds
#define FXLAB_ID_KEY_CORE_MOVIE_CLOUDS			517
#define FXLAB_ID_KEY_MOVIE_CLOUDS				518

//Quad Bow
#define FXLAB_ID_KEY_CORE_QUAD_SPARK		519
#define FXLAB_ID_KEY_QUAD_SPARK_POSITION	520
#define FXLAB_ID_KEY_QUAD_SPARK_VELOCITY	521
#define FXLAB_ID_KEY_QUAD_SPARK				522

#define FXLAB_ID_KEY_QUAD_OMNI				523
#define FXLAB_ID_KEY_QUAD_BOW				524

#define FXLAB_ID_KEY_QUAD_SET				525

//Movie Sparks
#define FXLAB_ID_KEY_CORE_MOVIE_SPARK		526

//MechosBubbles
#define FXLAB_ID_KEY_CORE_MOVIE_BUBBLE			527
#define FXLAB_ID_KEY_MOVIE_BUBBLE_POSITION		528
#define FXLAB_ID_KEY_MOVIE_BUBBLE_VELOCITY		529
#define FXLAB_ID_KEY_MOVIE_BUBBLE				530
  
//Perestroyka
#define FXLAB_ID_KEY_PERESTROYKA_CLAW_CONTROL	531

//Movie Shifter
#define FXLAB_ID_KEY_MASS_SHIFTER_MOVIE			532
#define FXLAB_ID_KEY_MASS_SHIFTER_MODEL_MOVIE	533

//TreeFire
#define FXLAB_ID_KEY_MOVIE_TREE_FIRE_POSITION	534
#define FXLAB_ID_KEY_MOVIE_TREE_FIRE_VELOCITY	535
#define FXLAB_ID_KEY_MOVIE_TREE_FIRE			536
#define FXLAB_ID_KEY_CORE_MOVIE_TREE_FIRE		537

//------------------

#define FXLAB_ID_KEY_TELEPORT_MOVIE_MODEL		538

//------------------

#define FXLAB_ID_KEY_MOVIE_BOSS_CHANGE_OMNI			539
#define FXLAB_ID_KEY_MOVIE_BOSS_CHANGE_DEFORMATION	540

//-----------------

#define FXLAB_ID_KEY_CORE_CHARACTER_BUBBLE			541
#define FXLAB_ID_KEY_CHARACTER_BUBBLE_POSITION		542
#define FXLAB_ID_KEY_CHARACTER_BUBBLE_VELOCITY		543
#define FXLAB_ID_KEY_CHARACTER_BUBBLE				544

#define FXLAB_ID_KEY_CORE_BOSS_STEAM				545
#define FXLAB_ID_KEY_BOSS_STEAM_TAIL_POSITION		546
#define FXLAB_ID_KEY_BOSS_STEAM_TAIL_VELOCITY		547
#define FXLAB_ID_KEY_BOSS_STEAM_TAIL				548

#define FXLAB_ID_KEY_CORE_BOSS_SMOKE				549
#define FXLAB_ID_KEY_BOSS_SMOKE_TAIL_POSITION		550
#define FXLAB_ID_KEY_BOSS_SMOKE_TAIL_VELOCITY		551
#define FXLAB_ID_KEY_BOSS_SMOKE_TAIL				552

#define FXLAB_ID_KEY_CHARACTER_WAVE_MODEL			553

#define FXLAB_ID_KEY_CORE_WATERFALL_FOG				554
#define FXLAB_ID_KEY_WATERFALL_FOG_POSITION			555
#define FXLAB_ID_KEY_WATERFALL_FOG_VELOCITY			556
#define FXLAB_ID_KEY_WATERFALL_FOG					557

//Boss Water
#define FXLAB_ID_KEY_BOSS_WATER_POSITION			558
#define FXLAB_ID_KEY_BOSS_WATER_VELOCITY			559
#define FXLAB_ID_KEY_BOSS_WATER_STREAM				560
#define FXLAB_ID_KEY_BOSS_WATER_CLUSTER				561
#define FXLAB_ID_KEY_CORE_BOSS_WATER				562

//Character World Burst
#define FXLAB_ID_KEY_CHARACTER_WORLD_BURST_POSITION	563
#define FXLAB_ID_KEY_CHARACTER_WORLD_BURST_VELOCITY	564
#define FXLAB_ID_KEY_CHARACTER_WORLD_BURST			565
#define FXLAB_ID_KEY_CORE_CHARACTER_WORLD_BURST		566
#define FXLAB_ID_KEY_CHARACTER_WORLD_OMNI			567

//Character World Burst
#define FXLAB_ID_KEY_CHARACTER_WORLD_EXPLOSION_POSITION	568
#define FXLAB_ID_KEY_CHARACTER_WORLD_EXPLOSION_VELOCITY	569
#define FXLAB_ID_KEY_CHARACTER_WORLD_EXPLOSION			570
#define FXLAB_ID_KEY_CORE_CHARACTER_WORLD_EXPLOSION		571

//BlueSlimeLarge
#define FXLAB_ID_KEY_BLUE_SLIME_LARGE_MODEL					572
#define FXLAB_ID_KEY_BLUE_SLIME_LARGE_CIRCLE				573

//Movie Dragon Fire
#define FXLAB_ID_KEY_MOVIE_DRAGON_FIRE_POSITION			574
#define FXLAB_ID_KEY_MOVIE_DRAGON_FIRE_VELOCITY			575
#define FXLAB_ID_KEY_MOVIE_DRAGON_FIRE					576
#define FXLAB_ID_KEY_CORE_MOVIE_DRAGON_FIRE				577

//Movie Rocket Fire
#define FXLAB_ID_KEY_MOVIE_ROCKET_FIRE_POSITION			578
#define FXLAB_ID_KEY_MOVIE_ROCKET_FIRE_VELOCITY			579
#define FXLAB_ID_KEY_MOVIE_ROCKET_FIRE					580
#define FXLAB_ID_KEY_CORE_MOVIE_ROCKET_FIRE				581

#define FXLAB_ID_KEY_MOVIE_ROCKET_SMOKE_POSITION		582
#define FXLAB_ID_KEY_MOVIE_ROCKET_SMOKE_VELOCITY		583
#define FXLAB_ID_KEY_MOVIE_ROCKET_SMOKE					584
#define FXLAB_ID_KEY_CORE_MOVIE_ROCKET_SMOKE			585

#define FXLAB_ID_KEY_MOVIE_ROCKET_OMNI					586

//----------------------------------------------------------

#define FXLAB_MODEL_INTERFACE_ID_CANNON_START		205
#define FXLAB_MODEL_INTERFACE_ID_CANNON_NOISE		0

#define FXLAB_MODEL_INTERFACE_ID_BOLIDE_START		200
#define FXLAB_MODEL_INTERFACE_ID_BOLIDE_NOISE		5

#define FXLAB_MODEL_INTERFACE_ID_VOLCANO_START		202
#define FXLAB_MODEL_INTERFACE_ID_VOLCANO_NOISE		0

#define FXLAB_MODEL_INTERFACE_ID_SNOW_START			212
#define FXLAB_MODEL_INTERFACE_ID_SNOW_NOISE			0

#define FXLAB_MODEL_INTERFACE_ID_SPLINTER_START		211
#define FXLAB_MODEL_INTERFACE_ID_SPLINTER_NOISE		0

#define FXLAB_MODEL_INTERFACE_ID_MORTAR_START		210
#define FXLAB_MODEL_INTERFACE_ID_MORTAR_MOISE		0

#define FXLAB_MODEL_INTERFACE_ID_BOX_START			206
#define FXLAB_MODEL_INTERFACE_ID_BOX_NOISE			4

